@baseUrl=https://localhost:5001
#@accountId=4285effc-d0a0-43bb-88b9-34932df50117
@accountId=ecf09339-34e0-464b-a8fb-661209048543
@tenantId=12d98746-0b5a-4778-8bd0-449994469062
@catalogId=ef5af140-62b9-431f-89be-2cdfcb0bf3a8
@apiVersion=2024-02-01-preview
@apiVersion2023=2023-10-01-preview

### List All Scores
GET {{baseUrl}}/scores?api-version=2024-02-01-preview
accept: application/json
content-type: application/json
x-ms-account-id: {{accountId}}
x-ms-client-tenant-id: {{tenantId}}
x-ms-catalog-id: {{catalogId}}

### Query Control Group Scores - Primary Route
POST {{baseUrl}}/scores/query?type=ControlGroup&api-version={{apiVersion}}
accept: application/json
content-type: application/json
x-ms-account-id: {{accountId}}
x-ms-client-tenant-id: {{tenantId}}
x-ms-catalog-id: {{catalogId}}

{
  "controlGroupIds": [
    "0fc05c66-727f-439f-9ac3-a988591df553",
    "8a7b81a0-805a-4cd0-96d5-5fb141b71f91",
    "c739cdca-eadc-482a-81a7-6f4f84958f03",
    "a340bd5f-3f68-4f09-b22e-f1e3aa35f74c",
    "b506f24f-fec3-4fb0-bf01-ae6b04c38af2",
    "4e8bcc42-61a7-4e82-926d-bb097ec0dfd3",
    "062e80d4-b947-4989-ba39-5fb7b8bc17c2"
  ],
  "domainIds": [],
  "recordLatestCounts": 35,
  "recordTimeRange": {
    "start": "2025-01-16T21:48:53.130Z",
    "end": "2025-02-15T21:48:53.130Z"
  }
}

### KickOffBackfill Catalog Events
POST {{baseUrl}}/controlplane/genevaAction/kickOffCatalogBackfill?api-version={{apiVersion}}
accept: application/json
content-type: application/json
x-ms-account-id: {{accountId}}
x-ms-client-tenant-id: {{tenantId}}
x-ms-catalog-id: {{catalogId}}

{
  "accountIds": ["ecf09339-34e0-464b-a8fb-661209048543"],
  "batchAmount": 2,
  "bufferTimeInMinutes": 2
}

### Query Control Group Scores - Secondary Route
PUT {{baseUrl}}/controls/schedule?api-version={{apiVersion}}
accept: application/json
content-type: application/json
x-ms-account-id: {{accountId}}
x-ms-client-tenant-id: {{tenantId}}
x-ms-catalog-id: {{catalogId}}

{
  "frequency": "Day",
  "interval": 1,
  "startTime": "2025-03-26T08:00:00Z",
  "timeZone": "UTC-11",
  "endTime": "2026-02-05T08:00:00Z",
  "status": "Enabled",
  "systemData": {
    "createdAt": "2024-04-25T15:57:49.2091218Z",
    "lastModifiedAt": "2025-02-27T14:12:29.2688889Z",
    "lastModifiedBy": "4cd28720-6c4f-41e4-9008-06711b5a46b0"
  }
}



### Validate Location URL Required field
Post {{baseUrl}}/settings/storageConfig/connectivity?api-version={{apiVersion}}
accept: application/json
content-type: application/json
x-ms-account-id: {{accountId}}
x-ms-client-tenant-id: {{tenantId}}
x-ms-catalog-id: {{catalogId}}

 {
  "type": "Fabric",
  "typeProperties": {
    "locationURL": "https://onelake.dfs.fabric.microsoft.com/TestWSPDGBB/testlakehouseBB.Lakehouse/Files/DEH1"
  },
  "status": "Enabled"
}

### Query Control Group Scores - Primary Route  "3d40e233-d431-4b56-af09-de5b0652d8bf" OKR
POST {{baseUrl}}/controls/schedule/trigger?api-version={{apiVersion}}
accept: application/json
content-type: application/json
x-ms-account-id: {{accountId}}
x-ms-client-tenant-id: {{tenantId}}
x-ms-catalog-id: {{catalogId}}

{
  //"controlId": "3d40e233-d431-4b56-af09-de5b0652d8bf"
  "controlId": "37ac2bdb-39c1-467f-8da1-823b16135305"
}

### Trigger Schedule Job
POST {{baseUrl}}/internal/control/triggerScheduleJob?api-version={{apiVersion}}
content-type: application/json
accept: application/json
x-ms-account-id: {{accountId}}
x-ms-client-tenant-id: {{tenantId}}

{
  "operator": "DGScheduleService",
  "triggerType": "Schedule"
}

### Create or Update Global Schedule
PUT {{baseUrl}}/controls/schedule?api-version={{apiVersion}}
accept: application/json
content-type: application/json
x-ms-account-id: {{accountId}}
x-ms-client-tenant-id: {{tenantId}}
x-ms-catalog-id: {{catalogId}}

{
  "frequency": "Day",
  "interval": 1,
  "startTime": "2025-05-21T08:00:00Z",
  "timeZone": "UTC",
  "status": "Enabled"
}

### Account Create or Update
PUT {{baseUrl}}/controlplane/account?api-version={{apiVersion}}
accept: application/json
content-type: application/json
x-ms-account-id: {{accountId}}
x-ms-client-tenant-id: {{tenantId}}
x-ms-catalog-id: {{catalogId}}

{
  "id": "{{accountId}}",
  "tenantId": "{{tenantId}}",
  "defaultCatalogId": "{{catalogId}}",
  "location": "westus2"
}