package com.microsoft.azurepurview.dataestatehealth.dimensionalmodel.fact
import org.apache.spark.sql.types._

class FactDataGovernanceScanSchema {
  val factDataGovernanceScanSchema: StructType = StructType(
    Array(
      StructField("HealthControlId", IntegerType, nullable = false),
      StructField("DataProductId", StringType, nullable = false),
      StructField("DEHProcessingDateId", LongType, nullable = false),
      StructField("LastProcessedDatetime", TimestampType, nullable = false),
      StructField("BusinessDomainId", StringType, nullable = true),
      StructField("TotalDataProductAssetCount", IntegerType, nullable = true),
      StructField("DataProductCounter", IntegerType, nullable = true),
      StructField("ClassifiedAssetCount", IntegerType, nullable = true),
      StructField("DataProductClassificationScore", DoubleType, nullable = true),
      StructField("DataProductIsClassified", IntegerType, nullable = true),
      StructField("LabeledAssetCount", IntegerType, nullable = true),
      StructField("DataProductLabelScore", DoubleType, nullable = true),
      StructField("DataProductIsLabeled", IntegerType, nullable = true),
      StructField("DataProductOwnerScore", DoubleType, nullable = true),
      StructField("DataProductHasOwner", IntegerType, nullable = true),
      StructField("DataProductDataAssetHasOwnerCount", IntegerType, nullable = true),
      StructField("DataProductObservabilityScore", DoubleType, nullable = true),
      StructField("DataProductAssetLinkageScore", DoubleType, nullable = true),
      StructField("DataProductAssetDQEnabledCount", IntegerType, nullable = true),
      StructField("DataProductAssetDQNotEnabledCount", IntegerType, nullable = true),
      StructField("DataProductAssetDQEnabledScore", DoubleType, nullable = true),
      StructField("DataProductCompositeDQScore", DoubleType, nullable = true),
      StructField("DataProductOKRLinkageScore", DoubleType, nullable = true),
      StructField("DataProductOKRLinkageCount", IntegerType, nullable = true),
      StructField("DataProductCriticalDataLinkageScore", DoubleType, nullable = true),
      StructField("DataProductCriticalDataLinkageCount", IntegerType, nullable = true),
      StructField("DataProductSelfServiceEnablementScore", DoubleType, nullable = true),
      StructField("DataProductSelfServiceAccessPolicyCount", IntegerType, nullable = true),
      StructField("DataProductSelfServiceDurationPolicyCount", IntegerType, nullable = true),
      StructField("DataProductSelfServiceSLAPolicyCount", IntegerType, nullable = true),
      StructField("DataProductComplianceDataTermsOfUsePolicyScore", DoubleType, nullable = true),
      StructField("DataProductComplianceDataTermsOfUsePolicyCount", IntegerType, nullable = true),
      StructField("DataProductPublishedCount", IntegerType, nullable = true),
      StructField("DataProductDraftCount", IntegerType, nullable = true),
      StructField("DataProductExpiredCount", IntegerType, nullable = true),
      StructField("DataProductHasDescription", IntegerType, nullable = true),
      StructField("DataProductHasAsset", IntegerType, nullable = true),
      StructField("DataProductHasPublishedGlossaryTerm", IntegerType, nullable = true),
      StructField("DataProductHasGlossaryTerm", IntegerType, nullable = true),
      StructField("DataProductHasUseCase", IntegerType, nullable = true),
      StructField("DataProductDataCatalogingScore", DoubleType, nullable = true),
      StructField("DataProductPublishedByAuthorizedUserCount", IntegerType, nullable = true),
      StructField("DataProductAssetMDQEnabledCount", IntegerType, nullable = true),
      StructField("DataProductAssetMDQNotEnabledCount", IntegerType, nullable = true),
      StructField("DataProductAssetMDQEnabledScore", DoubleType, nullable = true),
      StructField("DataProductCertifiedCount", IntegerType, nullable = true),
      StructField("DataProductAccessGrantCount", IntegerType, nullable = true),
      StructField("DataProductInSLAAccessGrantCount", IntegerType, nullable = true),
      StructField("DataProductAccessGrantScore", DoubleType, nullable = true),
      StructField("DataProductDescHasLenGr100Char", IntegerType, nullable = true),
      StructField("DataProductAssoBusinessDomainDescHasLenGr100Char", IntegerType, nullable = true),
      StructField("DataProductAssoAllTremDescHasLenGr25Char", IntegerType, nullable = true),
      StructField("DataProductUsabilityScore", DoubleType, nullable = true),
      StructField("DataProductHasParentBusinessDomain", IntegerType, nullable = true),
      StructField("DataProductHasAtLeast1Asset", IntegerType, nullable = true),
      StructField("DataProductHasAssoPubTerm", IntegerType, nullable = true),
      StructField("LinkedAssetsScore", DoubleType, nullable = true),
      StructField("DataProductAllAssoAssetsHasOwners", IntegerType, nullable = true),
      StructField("OwnershipScore", DoubleType, nullable = true)
    )
  )
}