// -----------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All rights reserved.
// -----------------------------------------------------------

namespace Microsoft.Azure.Purview.DataEstateHealth.Models;

using System.Security;
using System.Security.Cryptography;

/// <summary>
/// Credential object for power bi
/// </summary>
public class PowerBICredential
{
    /// <summary>
    /// The credential object for accessing a power bi dataset
    /// </summary>
    public PowerBICredential(Guid accountId, string location, string owner)
    {
        // Login is generated by the region. User name is generated by the account Id.
        byte[] inputBytes = System.Text.Encoding.ASCII.GetBytes(accountId.ToString());
        byte[] hashBytes = SHA256.HashData(inputBytes);

        string loginAndUserName = $"{owner}_{Convert.ToHexString(hashBytes)}";
        this.UserName = loginAndUserName;
        this.LoginName = loginAndUserName;
        this.CredentialSecretKey = $"{location.ToLower()}login";
    }

    /// <summary>
    /// The sql login name
    /// </summary>
    public string LoginName { get; }

    /// <summary>
    /// The key-vault-secret-key
    /// </summary>
    public string CredentialSecretKey { get; }

    /// <summary>
    /// The user name
    /// </summary>
    public string UserName { get; }

    /// <summary>
    /// The password
    /// </summary>
    public SecureString Password { get; set; }
}
