{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SERVER\",\"DATABASE\",\"DATABASE_SCHEMA\",\"BusinessDomain\",\"BusinessDomainTrends\",\"DataAsset\",\"DataAssetContactAssociation\",\"DataProduct\",\"DataProductContactAssociation\",\"DataProductDataAssetAssociation\",\"GlossaryTerm\",\"BusinessDomainDataProductAssociation\",\"TENANT_ID\",\"AssetURLTable\",\"AccountInfo\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.742.0 (23.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "SERVER",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"dghdogfoodsynapse-ondemand.sql.azuresynapse.net\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a14b6f22-ea8d-4a8e-97f2-05710f062eb1"
      },
      {
        "name": "DATABASE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"health_1\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "953805ba-bf53-4776-ad5b-7ae663b34473"
      },
      {
        "name": "TENANT_ID",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"79e7043b-2d89-4454-9f07-1d8ceb3f0399\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "17e0cb58-b472-4281-a56f-7015df8fa2d7"
      }
    ],
    "relationships": [
      {
        "name": "04fd2fa3-1df4-435c-a980-961d44d421d4",
        "fromColumn": "DataAssetId",
        "fromTable": "DataAssetContactAssociation",
        "toColumn": "DataAssetId",
        "toTable": "DataAsset"
      },
      {
        "name": "e9b6f76b-5739-4f0f-895b-d3fb38551e94",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DataAssetId",
        "fromTable": "DataProductDataAssetAssociation",
        "toColumn": "DataAssetId",
        "toTable": "DataAsset"
      },
      {
        "name": "f704051b-1942-49b7-ae30-9bf8c1b491a2",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "BusinessDomainId",
        "fromTable": "BusinessDomainDataProductAssociation",
        "toColumn": "BusinessDomainId",
        "toTable": "BusinessDomain"
      },
      {
        "name": "07041328-47fa-4318-befc-74c5d3d34b4b",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DataProductId",
        "fromTable": "BusinessDomainDataProductAssociation",
        "toColumn": "DataProductId",
        "toTable": "DataProduct"
      },
      {
        "name": "a39ef729-2770-4609-b87d-2c7a7677f9ae",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DataProductId",
        "fromTable": "DataProductDataAssetAssociation",
        "toCardinality": "many",
        "toColumn": "DataProductId",
        "toTable": "BusinessDomainDataProductAssociation"
      },
      {
        "name": "6234c35b-8a28-c424-6d81-0bed833431dd",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "BusinessDomainId",
        "fromTable": "BusinessDomainTrends",
        "toColumn": "BusinessDomainId",
        "toTable": "BusinessDomain"
      },
      {
        "name": "98b23a6e-7285-414b-8dc9-fb1f2ff58bfe",
        "fromColumn": "DataProductId",
        "fromTable": "DataProductContactAssociation",
        "toColumn": "DataProductId",
        "toTable": "BusinessDomainDataProductAssociation"
      },
      {
        "name": "397fcb5c-e901-4e65-b897-8345c62b5eeb",
        "fromColumn": "DataProductId",
        "fromTable": "AssetURLTable",
        "toColumn": "DataProductId",
        "toTable": "BusinessDomainDataProductAssociation"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "BusinessDomain",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "212cb632-0b48-471f-a1aa-3a469eb3c09e",
            "sourceColumn": "BusinessDomainId",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainDisplayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "75f3b3b2-2ba0-40a1-a99e-53c5bd3c871c",
            "sourceColumn": "BusinessDomainDisplayName",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "08c01862-e173-4e62-b69a-ed5c8879aad9",
            "sourceColumn": "CreatedAt",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "3beb56d3-32d6-43f0-aa47-92e94d8c9057",
            "sourceColumn": "CreatedBy",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a4bb3cea-6aa4-44e6-96d8-2c99ee9a77f0",
            "sourceColumn": "ModifiedAt",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "2121ab79-072d-4384-8f6c-91425126e0e7",
            "sourceColumn": "ModifiedBy",
            "summarizeBy": "none"
          },
          {
            "name": "GlossaryTermCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3907d87a-7141-407c-977b-6949beb885e8",
            "sourceColumn": "GlossaryTermCount",
            "summarizeBy": "sum"
          },
          {
            "name": "DataProductCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "425f02e6-9961-4222-982c-280454a68013",
            "sourceColumn": "DataProductCount",
            "summarizeBy": "sum"
          },
          {
            "name": "IsRootDomain",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8e39a308-b872-4700-8e7d-ce9bfa97f261",
            "sourceColumn": "IsRootDomain",
            "summarizeBy": "none"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1540c7e8-9007-48e8-a2e2-f9948f52e22f",
            "sourceColumn": "LastRefreshedAt",
            "summarizeBy": "none"
          },
          {
            "name": "HasValidOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d623da40-2e4e-43dc-af07-50e0e3e293b7",
            "sourceColumn": "HasValidOwner",
            "summarizeBy": "none"
          },
          {
            "name": "HasDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "98e0d34a-2072-4c16-9174-d3ce094482d1",
            "sourceColumn": "HasDescription",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bb22e2b4-7b67-4278-bc82-0426adf76ee0",
        "partitions": [
          {
            "name": "BusinessDomain",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomain\" = Source{[Schema= DATABASE_SCHEMA,Item=\"BusinessDomain\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomain\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BusinessDomainTrends",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BusinessDomainTrendId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "06c090aa-0a25-4ca5-99a5-717053f799a8",
            "sourceColumn": "BusinessDomainTrendId",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "33b8338e-8f90-4470-934a-8586ee981f19",
            "sourceColumn": "BusinessDomainId",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b1b99c18-c54f-46d4-958a-5b57c1721e72",
            "sourceColumn": "DataProductCount",
            "summarizeBy": "sum"
          },
          {
            "name": "AssetCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "48b4dd73-0802-4cec-b32b-4e5ab3d6ef2e",
            "sourceColumn": "AssetCount",
            "summarizeBy": "sum"
          },
          {
            "name": "ClassificationPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e913fd3-503b-49f8-a31b-21cb5004f942",
            "sourceColumn": "ClassificationPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "GlossaryTermPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a55ec180-4a5b-47ce-a84b-685395c2506c",
            "sourceColumn": "GlossaryTermPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "DataQualityScorePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e9d8d89d-e181-4113-b068-30818381efee",
            "sourceColumn": "DataQualityScorePassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "ValidDataProductOwnerPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1fd02d44-f020-4ff8-a0f6-9504390d2e80",
            "sourceColumn": "ValidDataProductOwnerPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "DataShareAgreementSetOrExemptPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d8f00ed5-d02b-43b6-805f-376b7395c218",
            "sourceColumn": "DataShareAgreementSetOrExemptPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "ValidUseCasePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "728b37aa-9a06-426f-89c6-26541f15ee1b",
            "sourceColumn": "ValidUseCasePassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "ValidTermsOfUsePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "55f542c4-287f-49ed-bb62-fc70817b339c",
            "sourceColumn": "ValidTermsOfUsePassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "AccessEntitlementPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9fb4438e-0e01-4aad-8185-c9edb551f680",
            "sourceColumn": "AccessEntitlementPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm d\\, yyyy",
            "lineageTag": "50bf2db3-bef9-454d-9c9d-7557b81b5469",
            "sourceColumn": "LastRefreshedAt",
            "summarizeBy": "none"
          },
          {
            "name": "TotalOpenActionsCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3e8afa3-9a47-4d1e-b09d-80363a87d37d",
            "sourceColumn": "TotalOpenActionsCount",
            "summarizeBy": "sum"
          },
          {
            "name": "DataProductDescriptionPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3897a97-3cad-4ad7-b375-f5bd0d9ead19",
            "sourceColumn": "DataProductDescriptionPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "AuthoritativeSourcePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f5c36bc-d55b-48ad-9959-614d21bd9899",
            "sourceColumn": "AuthoritativeSourcePassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm d\\, yyyy",
            "lineageTag": "a4586e51-3a33-42fb-beaa-5e2fafbd4552",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "91ac7ecd-d41a-4a53-8173-65b4983ce7b8",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d6ae76ed-5409-4399-b782-f93c0a38a783",
        "measures": [
          {
            "name": "Trend_Metadata completeness",
            "expression": "DIVIDE(BusinessDomainTrends[Trend_Metadata completeness pass count],SUM(BusinessDomainTrends[DataProductCount]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c0b8c886-486a-4d4c-bdf6-7f7d6d88ce16"
          },
          {
            "name": "Trend_Metadata completeness pass count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "(SUM('BusinessDomainTrends'[ClassificationPassCount])+",
              "SUM('BusinessDomainTrends'[ValidDataProductOwnerPassCount])+SUM(BusinessDomainTrends[DataProductDescriptionPassCount])+SUM(BusinessDomainTrends[GlossaryTermPassCount])+SUM(BusinessDomainTrends[ValidUseCasePassCount])+SUMX(BusinessDomainTrends,BusinessDomainTrends[Trend_Asset Pass count])",
              ")/6"
            ],
            "lineageTag": "2b5906bd-a5fa-477e-a8f6-f66845f465d6"
          },
          {
            "name": "Trend_Quality pass count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "(SUM('BusinessDomainTrends'[DataQualityScorePassCount])+",
              "SUM('BusinessDomainTrends'[AuthoritativeSourcePassCount]))/2"
            ],
            "lineageTag": "0f014697-4f30-475a-898a-63e0938a2523"
          },
          {
            "name": "Trend_Use pass count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "(sum('BusinessDomainTrends'[DataShareAgreementSetOrExemptPassCount])+",
              "sum('BusinessDomainTrends'[AccessEntitlementPassCount]))/2"
            ],
            "lineageTag": "e0e00cf1-4194-410e-a800-7e49ec4530e1"
          },
          {
            "name": "Trend_Sum of all metrics",
            "expression": [
              "",
              "SUM(BusinessDomainTrends[ValidDataProductOwnerPassCount])+",
              "SUM(BusinessDomainTrends[ClassificationPassCount])+",
              "SUM(BusinessDomainTrends[DataQualityScorePassCount])+",
              "SUM(BusinessDomainTrends[AuthoritativeSourcePassCount])+",
              "SUM(BusinessDomainTrends[AccessEntitlementPassCount])+",
              "SUM(BusinessDomainTrends[DataShareAgreementSetOrExemptPassCount])+",
              "SUM(BusinessDomainTrends[DataProductDescriptionPassCount])+",
              "SUM(BusinessDomainTrends[GlossaryTermPassCount])+",
              "SUM(BusinessDomainTrends[ValidUseCasePassCount])+",
              "SUMX(BusinessDomainTrends,BusinessDomainTrends[Trend_Asset Pass count])",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f7e9d30f-be49-464c-bf16-670acb4219e8"
          },
          {
            "name": "Trend_Overall health score",
            "expression": "DIVIDE([Trend_Sum of all metrics],SUM('BusinessDomainTrends'[DataProductCount])*10)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "fa4abfc3-413d-4229-b8df-134e07c870c7"
          },
          {
            "name": "Trend_Quality",
            "expression": "DIVIDE([Trend_Quality pass count],sum('BusinessDomainTrends'[DataProductCount]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "bba3ffdc-bccc-4086-9755-0fe4eca2ec02"
          },
          {
            "name": "Trend_Use",
            "expression": "DIVIDE([Trend_Use pass count],sum('BusinessDomainTrends'[DataProductCount]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5c59a53d-e2d1-42ed-a0c5-8e3953391799"
          },
          {
            "name": "Trend_Asset Pass count",
            "expression": [
              "CALCULATE(COUNT('DataProduct'[DataProductId]),",
              "'DataProduct'[Assetcount_catalog P/F] = \"Pass\")"
            ],
            "formatString": "0",
            "lineageTag": "f539233d-7090-4b2c-bd5a-b10780f26066"
          },
          {
            "name": "Sum of Asset pass count",
            "expression": "SUMX(BusinessDomainTrends,BusinessDomainTrends[Trend_Asset Pass count])",
            "formatString": "0",
            "lineageTag": "533391d1-545e-45af-9d0c-996f3251658f"
          }
        ],
        "partitions": [
          {
            "name": "BusinessDomainTrends",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomainTrends\" = Source{[Schema=DATABASE_SCHEMA,Item=\"BusinessDomainTrends\"]}[Data],",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomainTrends\", \"LastRefreshedAt\", \"LastRefreshedAt - Copy\"),",
                "    #\"Inserted Date\" = Table.AddColumn(#\"Duplicated Column\", \"Date\", each Date.From([#\"LastRefreshedAt - Copy\"]), type date),",
                "    #\"Split Column by Positions\" = Table.SplitColumn(Table.TransformColumnTypes(#\"Inserted Date\", {{\"LastRefreshedAt - Copy\", type text}}, \"en-US\"), \"LastRefreshedAt - Copy\", Splitter.SplitTextByPositions({0, 11}), {\"LastRefreshedAt - Copy.1\", \"LastRefreshedAt - Copy.2\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Split Column by Positions\",{{\"LastRefreshedAt - Copy.1\", type date}, {\"LastRefreshedAt - Copy.2\", type time}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"LastRefreshedAt - Copy.1\", \"Date1\"}, {\"LastRefreshedAt - Copy.2\", \"Time\"}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Date\"}),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Removed Columns\",{{\"Date1\", \"Date\"}})",
                "in",
                "    #\"Renamed Columns1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DataAsset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DataAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e39026af-ff1f-434e-9062-5b5c98fb7a68",
            "sourceColumn": "DataAssetId",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f1e9149d-ec74-4fce-a79e-70964e721c76",
            "sourceColumn": "CreatedAt",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "91eb7a17-9539-4015-8baa-91f543df2229",
            "sourceColumn": "CreatedBy",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f7de614-5aa1-40e8-be9b-eb3e96afaab5",
            "sourceColumn": "ModifiedBy",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "40711738-1686-471a-acda-9ca6c8d7b098",
            "sourceColumn": "ModifiedAt",
            "summarizeBy": "none"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d96ae37b-f12a-43e7-84af-41f6f2908812",
            "sourceColumn": "LastRefreshedAt",
            "summarizeBy": "none"
          },
          {
            "name": "SourceType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "742cc15a-4dc4-4d9e-9b76-c5603dddb9ac",
            "sourceColumn": "SourceType",
            "summarizeBy": "none"
          },
          {
            "name": "ObjectType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0fad8f6-34aa-4c3d-a885-3a133b725801",
            "sourceColumn": "ObjectType",
            "summarizeBy": "none"
          },
          {
            "name": "HasSchema",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "5f1f365b-63fe-4264-8e64-8f2e8b0ca6d8",
            "sourceColumn": "HasSchema",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b33a5eff-5c11-4283-a558-03b47eaa9275",
            "sourceColumn": "BusinessDomainId",
            "summarizeBy": "none"
          },
          {
            "name": "SourceAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "917b9909-257f-4aba-b87e-af54d4c6d5d3",
            "sourceColumn": "SourceAssetId",
            "summarizeBy": "none"
          },
          {
            "name": "DisplayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ae23736-3006-4d6c-afa3-1d6061bed88b",
            "sourceColumn": "DisplayName",
            "summarizeBy": "none"
          },
          {
            "name": "HasClassification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c73d33cd-137a-4338-87f0-0390894a06de",
            "sourceColumn": "HasClassification",
            "summarizeBy": "none"
          },
          {
            "name": "HasDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "cec1fb47-ccff-4e66-8e4c-735d5bae6563",
            "sourceColumn": "HasDescription",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e01a6210-45a2-498b-a38a-192cae8264e8",
        "partitions": [
          {
            "name": "DataAsset",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataAsset\" = Source{[Schema= DATABASE_SCHEMA,Item=\"DataAsset\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataAsset\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DataAssetContactAssociation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DataAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9eb9f08-4787-4e2e-bf47-756c7072bb2f",
            "sourceColumn": "DataAssetId",
            "summarizeBy": "none"
          },
          {
            "name": "ContactRole",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "fbab66b3-3042-44cc-b653-2c714744fc1e",
            "sourceColumn": "ContactRole",
            "summarizeBy": "none"
          },
          {
            "name": "ContactId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ff104b9-23a3-4036-8b99-8e5135f8cec5",
            "sourceColumn": "ContactId",
            "summarizeBy": "none"
          },
          {
            "name": "IsActive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f5837da1-df40-4a24-901c-d8f58ec95f88",
            "sourceColumn": "IsActive",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f6784168-2d61-407e-a710-15511338caef",
        "partitions": [
          {
            "name": "DataAssetContactAssociation",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataAssetContactAssociation\" = Source{[Schema = DATABASE_SCHEMA,Item=\"DataAssetContactAssociation\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataAssetContactAssociation\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DataProduct",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "db0c9ab9-0f2d-4fed-8b70-b2279dac8c4f",
            "sourceColumn": "DataProductId",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductDisplayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a39dbf37-4089-4f07-9552-4da49c3b6fa4",
            "sourceColumn": "DataProductDisplayName",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f618f6d-0ac1-4f60-be42-32cf40567a53",
            "sourceColumn": "DataProductType",
            "summarizeBy": "none"
          },
          {
            "name": "HasValidOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "df42f1c6-5b80-4516-8bf4-e96394cb19cd",
            "sourceColumn": "HasValidOwner",
            "summarizeBy": "none"
          },
          {
            "name": "HasValidUseCase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ad4067cc-72a9-4c38-a947-45a17093c2e7",
            "sourceColumn": "HasValidUseCase",
            "summarizeBy": "none"
          },
          {
            "name": "AssetCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "26f5dc91-2a0f-4962-9798-ce1088adf767",
            "sourceColumn": "AssetCount",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ae87c72b-772c-4500-9c27-b6b2c94fe6c0",
            "sourceColumn": "CreatedAt",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8dd7633-e73e-46bd-9571-6a4c7e1d361d",
            "sourceColumn": "CreatedBy",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "0b0cabc2-f4a3-463a-ae80-93532959cbab",
            "sourceColumn": "ModifiedAt",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "5707fdc7-b70b-41f4-91a2-c96f61b6b2f1",
            "sourceColumn": "ModifiedBy",
            "summarizeBy": "none"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "cee8dcaf-70f8-47bf-a718-f7ad440326ac",
            "sourceColumn": "LastRefreshedAt",
            "summarizeBy": "none"
          },
          {
            "name": "IsAuthoritativeSource",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "cea7db2f-53b8-4e69-acb3-fd6b1649028d",
            "sourceColumn": "IsAuthoritativeSource",
            "summarizeBy": "none"
          },
          {
            "name": "HasDataQualityScore",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0ab26c16-e9bf-4c61-8e4d-f486721fd7f4",
            "sourceColumn": "HasDataQualityScore",
            "summarizeBy": "none"
          },
          {
            "name": "ClassificationPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a126b99-65c8-4d6d-b958-ea8d100c1eba",
            "sourceColumn": "ClassificationPassCount",
            "summarizeBy": "none"
          },
          {
            "name": "HasAccessEntitlement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c59ed45b-910b-4e22-b602-d694829cdf81",
            "sourceColumn": "HasAccessEntitlement",
            "summarizeBy": "none"
          },
          {
            "name": "HasDataShareAgreementSetOrExempt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "79ad4ed1-5623-40f6-8aa7-ad0cbe8e95c0",
            "sourceColumn": "HasDataShareAgreementSetOrExempt",
            "summarizeBy": "none"
          },
          {
            "name": "GlossaryTermCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4a8c05c3-f5c0-4fd9-9d4d-c75e6fd2a351",
            "sourceColumn": "GlossaryTermCount",
            "summarizeBy": "none"
          },
          {
            "name": "Access entitlement P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF('DataProduct'[HasAccessEntitlement] = TRUE(),\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "6c0ec664-d767-456c-b0e1-0a53e842f4ad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Action Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "IF(",
              "                'DataProduct'[Owner P/F]= \"Fail\",1,0)",
              "                +IF('DataProduct'[Classification_Product P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Assetcount_catalog P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Glosssary Term count_catalog P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Description_catalog P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Valid use case_catalog P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Data Qualiy P/F] = \"Fail\", 1,0)",
              "                +IF('DataProduct'[Authoritative source P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Access entitlement P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Data consumption purpse P/F] = \"Fail\",1,0",
              "                )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2c87178d-3fa0-4f0d-9307-8a5c201c25f5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Authoritative source P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF('DataProduct'[IsAuthoritativeSource]= TRUE(),\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "91d8f8a6-65af-4f4b-95a4-19b3bb8a1f57",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Classification_Product P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(COALESCE('DataProduct'[ClassificationPassCount],0) > 0 , \"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "76d2386b-502f-4748-8ea5-5fa921ae906e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Data consumption purpse P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF('DataProduct'[HasDataShareAgreementSetOrExempt] = TRUE(), \"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "ba828d2a-4632-4b29-896c-d8f6e0d8cd47",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Data Qualiy P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF('DataProduct'[HasDataQualityScore] = TRUE() ,\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "9811b820-10ba-44d4-b769-3f6304e5d90a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Overall health staus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Overall health score] > [Max_Thresh hold], \"Healthy\", ",
              "                            [Overall health score] > [Min_Tresh hold] && [Overall health score] <=[Max_Thresh hold] , \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7314c5a9-fc97-430a-bc17-e2a197b06216",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Owner P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF('DataProduct'[HasValidOwner] = TRUE(), \"Pass\", \"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "1116f6a1-d103-4170-bd5b-e588adb8cd8e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Owner_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(COALESCE('DataProduct'[HasValidOwner],0) = TRUE(),\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "e56a65f7-dc4d-4a3e-ae24-a41ef7700310",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Valid use case_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(COALESCE('DataProduct'[HasValidUseCase],0) = TRUE() , \"Pass\", \"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "139fa52e-a368-4695-93c7-436fab867a0f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Assetcount_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(COALESCE('DataProduct'[Asset count],0) >= 1,\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "239fc81e-0ed9-4c93-91be-4b1f38cce209",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Description_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(COALESCE('DataProduct'[HasDescription],0) = TRUE(),\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "46edeabd-ad87-4538-ad4b-c9c6d0498c79",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Glosssary Term count_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(COALESCE('DataProduct'[GlossaryTermCount],0) > 0 ,\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "57cd768e-7c5e-4485-a4d2-55926428d5e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "HasDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f02d5487-6225-4e9b-a0c9-b38067c34ce8",
            "sourceColumn": "HasDescription",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e8f44bf-9d58-4d66-9c63-391fccaaa750",
            "sourceColumn": "DataProductStatus",
            "summarizeBy": "none"
          },
          {
            "name": "HasValidTermsOfUse",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0ea5692f-10b8-4d07-8843-fa94aae7f127",
            "sourceColumn": "HasValidTermsOfUse",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5e64d8f2-a51a-4abe-b8b8-86d5ed754fb7",
        "measures": [
          {
            "name": "1C2_Ownership",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Owner Pass count],[Total DataProducts])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ab20c77a-ed22-412c-9aee-96f1d4093cbc"
          },
          {
            "name": "1C3_Authoritative source",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Authoritative source Pass count],[Total DataProducts])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "635f12d3-631e-4325-9a8a-8e8e3ea0c0de"
          },
          {
            "name": "1C5_Catalog",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Catalog Pass count]/5,[Total DataProducts])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2ab18bee-5cb3-41cc-b2a9-e3ffe7150910"
          },
          {
            "name": "1C6_Classification",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Classifiaction pass count],[Total DataProducts])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "257a6f65-ca40-4a25-b60b-478186ade7b3"
          },
          {
            "name": "1C7_Access entitlement",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Access entitlement Pass count],[Total DataProducts])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "19dfa957-b968-4be9-bcaa-896dfe9fc6d5"
          },
          {
            "name": "1C8_Data consumption purpose",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "DIVIDE([Data consumption Purpose Pass count],[Total DataProducts])",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c3686e9a-4c21-4611-83dd-4fb0d92b4188"
          },
          {
            "name": "1Metadata completeness",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "DIVIDE(([Owner Pass count]+[Catalog Pass count_without owner pass]+[Classifiaction pass count])/6,",
              "[Total DataProducts])"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "650c41d3-8546-4ba5-8be9-4014a82b1e24"
          },
          {
            "name": "1Overall health score",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Sum of Pass Metrics],[Total DataProducts]*10)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5e767785-8cdd-406c-9a48-d0c068bec8c4"
          },
          {
            "name": "1Quality",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE(([Authoritative source Pass count]+[Data Quality Pass count])/2,[Total DataProducts])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "30116691-0393-410a-b703-19c76e84b690"
          },
          {
            "name": "1Use",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE(([Data consumption Purpose Pass count]+[Access entitlement Pass count])/2,[Total DataProducts])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ddd54794-cd9b-4f80-90a3-8a2a29048a01"
          },
          {
            "name": "Access entitlement health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C7_Access entitlement] > 0.5, \"Healthy\", ",
              "                            [C7_Access entitlement] > 0.2 && [C7_Access entitlement] <= 0.5 , \"Fair\",",
              "                            [C7_Access entitlement] <= 0.2, \"Not healthy\")"
            ],
            "lineageTag": "b7ffffc4-0719-43cb-a79d-53279abc5873"
          },
          {
            "name": "Access entitlement Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(DISTINCTCOUNT('DataProduct'[DataProductId]),",
              "'DataProduct'[Access entitlement P/F] = \"Pass\")+0"
            ],
            "formatString": "0",
            "lineageTag": "40fa872f-835e-4679-9052-8f8547a37610"
          },
          {
            "name": "Access entitlement tresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [C7_Access entitlement] > [Max_Thresh hold], \"#80D091\", ",
              "                            [C7_Access entitlement] >[Min_Tresh hold] && [C7_Access entitlement] <=[Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "ab5ad6bc-ff85-4d61-9b24-bd5c3772d3c2"
          },
          {
            "name": "Action item measure",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(sum('DataProduct'[Action Items]) = BLANK(),0,SUM('DataProduct'[Action Items]))",
            "formatString": "0",
            "lineageTag": "990c4ec0-d8bc-4f27-9879-86b4bce80455"
          },
          {
            "name": "Authoritative source health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C3_Authoritative source] > [Max_Thresh hold], \"Healthy\", ",
              "                            [C3_Authoritative source] >[Min_Tresh hold] && [C3_Authoritative source] <= 0.5 , \"Fair\",",
              "                            [C3_Authoritative source] <= 0.2, \"Not healthy\")"
            ],
            "lineageTag": "444d4604-3386-4cd4-846d-c320bf253902"
          },
          {
            "name": "Authoritative source Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(DISTINCTCOUNT('DataProduct'[DataProductId]),",
              "'DataProduct'[Authoritative source P/F] = \"Pass\")+0"
            ],
            "formatString": "0",
            "lineageTag": "887ea7f2-bcf9-4962-8f16-bc744e1906ca"
          },
          {
            "name": "Authoritative tresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [C3_Authoritative source] > [Max_Thresh hold], \" #80D091\", ",
              "                            [C3_Authoritative source] > [Min_Tresh hold] && [C3_Authoritative source] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "359dfd36-0299-4bb5-b9d1-2e77a355652e"
          },
          {
            "name": "C_12 Data quality",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Data Quality Pass count],[Total DataProducts]) <>BLANK(),DIVIDE([Data Quality Pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f315a253-ecdf-47db-bc8e-1c358c0d9030"
          },
          {
            "name": "C2_Ownership",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Owner Pass count],[Total DataProducts])<>BLANK(), DIVIDE([Owner Pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d0af49fd-f713-48b2-95ad-6d80adaabd97"
          },
          {
            "name": "C3_Authoritative source",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Authoritative source Pass count],[Total DataProducts]) <>BLANK(),DIVIDE([Authoritative source Pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5a5e09ab-0409-411f-a714-a3e844d3ef85"
          },
          {
            "name": "C5_Catalog",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Catalog Pass count]/5,[Total DataProducts])+0",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "566f3007-80ea-4c64-990d-790539da87d1"
          },
          {
            "name": "C6_Classification",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Classifiaction pass count],[Total DataProducts])<>BLANK(),DIVIDE([Classifiaction pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0057267d-3af5-4f98-a98b-c975fb2a8b03"
          },
          {
            "name": "C7_Access entitlement",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Access entitlement Pass count],[Total DataProducts])<>BLANK(),DIVIDE([Access entitlement Pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c41438bc-0a9a-46a9-af5d-11475af66d9a"
          },
          {
            "name": "C8_Data consumption purpose",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Data consumption Purpose Pass count],[Total DataProducts])<>BLANK(),DIVIDE([Data consumption Purpose Pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "58960f74-44b3-4bd4-8ee0-df42002d83c1"
          },
          {
            "name": "Catalog health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C5_Catalog] > [Max_Thresh hold], \"Healthy\", ",
              "                            [C5_Catalog] > [Min_Tresh hold] && [C5_Catalog] <=[Max_Thresh hold] , \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "2a781147-eb50-4ffd-8e3e-a8281d71e158"
          },
          {
            "name": "Catalog Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "var c1 = CALCULATE(COUNT('DataProduct'[Assetcount_catalog P/F]),'DataProduct'[Assetcount_catalog P/F] = \"Pass\")+0",
              "var c2 = CALCULATE(COUNT('DataProduct'[Glosssary Term count_catalog P/F]),'DataProduct'[Glosssary Term count_catalog P/F] = \"Pass\")+0",
              "var c3 = CALCULATE(COUNT('DataProduct'[Description_catalog P/F]),'DataProduct'[Description_catalog P/F] = \"Pass\")+0",
              "var c4 = CALCULATE(COUNT('DataProduct'[Owner_catalog P/F]),'DataProduct'[Owner_catalog P/F] = \"Pass\")+0",
              "var c5 = CALCULATE(COUNT('DataProduct'[Valid use case_catalog P/F]),'DataProduct'[Valid use case_catalog P/F] = \"Pass\")+0",
              "RETURN",
              "c1+c2+c3+c4+c5"
            ],
            "formatString": "0",
            "lineageTag": "799eeb76-a960-45bc-b976-1b177791ec26"
          },
          {
            "name": "Catalog tresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [C5_Catalog] > [Max_Thresh hold], \" #80D091\", ",
              "                            [C5_Catalog] > [Min_Tresh hold] && [C5_Catalog] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "3bb0813d-0b95-41cb-8b4f-431a75220e91"
          },
          {
            "name": "Classifiaction pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF(ISBLANK(CALCULATE(DISTINCTCOUNT('DataProduct'[DataProductId]),",
              "'DataProduct'[Classification_Product P/F] = \"Pass\")),0,",
              "CALCULATE(DISTINCTCOUNT('DataProduct'[DataProductId]),",
              "'DataProduct'[Classification_Product P/F] = \"Pass\"))"
            ],
            "formatString": "0",
            "lineageTag": "88716b25-a863-4e04-82b3-6d65fd5d6a5e"
          },
          {
            "name": "Classification health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C6_Classification] > [Max_Thresh hold], \"Healthy\", ",
              "                            [C6_Classification] >[Min_Tresh hold]&& [C6_Classification] <= [Max_Thresh hold], \"Fair\",",
              "                            \"Not healthy\")"
            ],
            "lineageTag": "e84628c8-ec41-4236-859e-21354ed88f44"
          },
          {
            "name": "Classification tresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                           ",
              "                            [C6_Classification] > [Max_Thresh hold], \" #80D091\", ",
              "                            [C6_Classification] > [Min_Tresh hold] && [C6_Classification] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "836b6889-86bd-4a9a-bcb6-0ad1a4aac353"
          },
          {
            "name": "Data consumption health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C8_Data consumption purpose] >[Max_Thresh hold], \"Healthy\", ",
              "                            [C8_Data consumption purpose] >[Min_Tresh hold] && [C8_Data consumption purpose] <= [Max_Thresh hold], \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "dace400e-2202-4a1b-9219-705a20357aa3"
          },
          {
            "name": "Data consumption Purpose Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(DISTINCTCOUNT('DataProduct'[DataProductId]),",
              "'DataProduct'[Data consumption purpse P/F] = \"Pass\")+0"
            ],
            "formatString": "0",
            "lineageTag": "7855a0ec-41a3-4265-b313-0bf7207d60ca"
          },
          {
            "name": "Data consumption tresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                           ",
              "                            [C8_Data consumption purpose] > [Max_Thresh hold], \" #80D091\", ",
              "                            [C8_Data consumption purpose] > [Min_Tresh hold] && [C8_Data consumption purpose] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "81caf6f8-0f01-4a0b-a430-909b617658e0"
          },
          {
            "name": "Data quality health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C_12 Data quality] >[Max_Thresh hold], \"Healthy\", ",
              "                            [C_12 Data quality] > [Min_Tresh hold] && [C_12 Data quality] <= [Max_Thresh hold], \"Fair\",",
              "                            \"Not healthy\")"
            ],
            "lineageTag": "416e646a-07c2-4fc1-bfe7-acee39ce095d"
          },
          {
            "name": "Data Quality Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF(ISBLANK(CALCULATE(DISTINCTCOUNT('DataProduct'[DataProductId]),",
              "'DataProduct'[Data Qualiy P/F] = \"Pass\")),0,",
              "CALCULATE(DISTINCTCOUNT('DataProduct'[DataProductId]),",
              "'DataProduct'[Data Qualiy P/F] = \"Pass\"))"
            ],
            "formatString": "0",
            "lineageTag": "8de7c777-329d-47d5-8454-a6299c3491a4"
          },
          {
            "name": "Data quality tresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "",
              "                            [C_12 Data quality] > [Max_Thresh hold], \" #80D091\", ",
              "                            [C_12 Data quality] > [Min_Tresh hold] && [C_12 Data quality] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "1bbf4b86-b8ab-409f-b8d7-5ae433350070"
          },
          {
            "name": "DummyTarget",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "0.5",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "bbf2d5af-8953-4ec0-8fcf-1047219c5f74"
          },
          {
            "name": "Max_Thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "0.9",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "9a461d76-b808-4fda-8d19-7b073bc50ee8"
          },
          {
            "name": "Metadata completeness",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "DIVIDE(([Owner Pass count]+[Catalog Pass count_without owner pass]+[Classifiaction pass count])/6,",
              "[Total DataProducts])+0"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dc3bd2a5-c74d-4898-9517-f75fbf05fe29"
          },
          {
            "name": "Metadata completeness status",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Metadata completeness] > [Max_Thresh hold], \"Healthy\", ",
              "                            [Metadata completeness] > [Min_Tresh hold] && [Metadata completeness] <= [Max_Thresh hold] , \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "b4cb6f86-f8f9-49ee-9c09-f9bad0b250f7"
          },
          {
            "name": "Metadata completeness tresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Metadata completeness] > [Max_Thresh hold], \" #80D091\", ",
              "                            [Metadata completeness] > [Min_Tresh hold] && [Metadata completeness] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "090cf046-3d2f-45ef-aa54-51b8fe474c28"
          },
          {
            "name": "Min_Tresh hold",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "0.5",
            "lineageTag": "e380079a-7aa7-45db-9608-733f7581af21"
          },
          {
            "name": "Overall health score",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Sum of Pass Metrics],[Total DataProducts]*10)+0",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "01d5ba84-97cc-4e95-9017-5e4f00782ca0"
          },
          {
            "name": "Overall health staus_measure",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Overall health score] > [Max_Thresh hold], \"Healthy\", ",
              "                            [Overall health score] > [Min_Tresh hold] && [Overall health score] <= [Max_Thresh hold], \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "33398188-377a-4f82-a59c-b2033adfe038"
          },
          {
            "name": "Overall health thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                           ",
              "                            [Overall health score] > [Max_Thresh hold], \" #80D091\", ",
              "                            [Overall health score] > [Min_Tresh hold] && [Overall health score] <= [Max_Thresh hold],\"#E8CC78\",",
              "                            ",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "bb297018-9b5e-4f7a-b5ea-f4ad72911b4a"
          },
          {
            "name": "Owner Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "IF(ISBLANK(CALCULATE(DISTINCTCOUNT('DataProduct'[DataProductId]),",
              "'DataProduct'[Owner P/F] = \"Pass\")),0,",
              "CALCULATE(DISTINCTCOUNT('DataProduct'[DataProductId]),",
              "'DataProduct'[Owner P/F] = \"Pass\"))"
            ],
            "formatString": "0",
            "lineageTag": "d9c88924-6f6f-4069-9fcd-3ab22c711971"
          },
          {
            "name": "Ownership health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C2_Ownership] >[Max_Thresh hold], \"Healthy\", ",
              "                            [C2_Ownership] > [Min_Tresh hold] && [C2_Ownership] <=[Max_Thresh hold] , \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "a7988ff8-6a26-4a75-9e5f-9c989dd2227d"
          },
          {
            "name": "Ownership tresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [C2_Ownership] > [Max_Thresh hold], \" #80D091\", ",
              "                            [C2_Ownership] > [Min_Tresh hold] && [C2_Ownership] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "14a55b68-dcfc-479a-acd4-5f9472bd377e"
          },
          {
            "name": "Quality",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE(([Authoritative source Pass count]+[Data Quality Pass count])/2,[Total DataProducts])<> BLANK(),DIVIDE(([Authoritative source Pass count]+[Data Quality Pass count])/2,[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "19a378de-e683-4eb8-9dd6-789066e5383a"
          },
          {
            "name": "Quality health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Quality] > [Max_Thresh hold], \"Healthy\", ",
              "                            [Quality] > [Min_Tresh hold] && [Quality] <= [Max_Thresh hold] , \"Fair\",",
              "                            \"Not healthy\")"
            ],
            "lineageTag": "ac883693-c0ec-4efd-b2c1-0b2702982e90"
          },
          {
            "name": "Quality tresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [Quality] > [Max_Thresh hold], \" #80D091\", ",
              "                            [Quality] > [Min_Tresh hold] && [Quality] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "e685dd30-db6a-4c37-9b1b-584a4af55873"
          },
          {
            "name": "Sum of Pass Metrics",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "[Owner Pass count]+",
              "[Catalog Pass count_without owner pass]+",
              "[Classifiaction pass count]+",
              "[Data Quality Pass count]+",
              "[Authoritative source Pass count]+",
              "[Access entitlement Pass count]+",
              "[Data consumption Purpose Pass count]"
            ],
            "formatString": "0",
            "lineageTag": "57d81210-f823-42ba-8773-d191d79199f8"
          },
          {
            "name": "Asset count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DISTINCTCOUNT(DataAsset[DataAssetId])",
            "formatString": "0",
            "lineageTag": "ac7da6b6-b54c-4b0d-97bc-443dfff75361"
          },
          {
            "name": "Total DataProducts",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DISTINCTCOUNT('DataProduct'[DataProductId])+0",
            "formatString": "0",
            "lineageTag": "b8618123-5a08-4245-9b93-1fb72213875e"
          },
          {
            "name": "Total Domains",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "COUNT('BusinessDomain'[BusinessDomainId])",
            "formatString": "0",
            "lineageTag": "8d3cc3df-6ae9-457d-befc-956cc7244cdc"
          },
          {
            "name": "Use",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE(([Data consumption Purpose Pass count]+[Access entitlement Pass count])/2,[Total DataProducts])<>BLANK(),DIVIDE(([Data consumption Purpose Pass count]+[Access entitlement Pass count])/2,[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "90258d2d-877d-4687-bf47-dc06ea0b7bff"
          },
          {
            "name": "Use heath staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Use] > [Max_Thresh hold], \"Healthy\", ",
              "                            [Use] > [Min_Tresh hold]&& [Use] <= [Max_Thresh hold], \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "457163e4-529f-40d5-8a95-ed5577b57980"
          },
          {
            "name": "Use tresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [Use] > [Max_Thresh hold], \" #80D091\", ",
              "                            [Use] > [Min_Tresh hold] && [Use] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "e7e0f6a9-3468-40be-8dbd-8e07ae198037"
          },
          {
            "name": "1C_12 Data quality",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Data Quality Pass count],[Total DataProducts])",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "39f71e58-9d38-47a8-9813-15580d99a782"
          },
          {
            "name": "Total assets",
            "expression": "SUMX(DataProduct,[Asset count])+0",
            "formatString": "0",
            "lineageTag": "8ddc5f73-4a8d-468d-bf70-0a1fbd9938e0"
          },
          {
            "name": "Catalog Pass count_without owner pass",
            "expression": [
              "var c1 = CALCULATE(COUNT('DataProduct'[Assetcount_catalog P/F]),'DataProduct'[Assetcount_catalog P/F] = \"Pass\")+0",
              "var c2 = CALCULATE(COUNT('DataProduct'[Glosssary Term count_catalog P/F]),'DataProduct'[Glosssary Term count_catalog P/F] = \"Pass\")+0",
              "var c3 = CALCULATE(COUNT('DataProduct'[Description_catalog P/F]),'DataProduct'[Description_catalog P/F] = \"Pass\")+0",
              "//var c4 = CALCULATE(COUNT('DataProduct'[Owner_catalog P/F]),'DataProduct'[Owner_catalog P/F] = \"Pass\")+0//",
              "var c5 = CALCULATE(COUNT('DataProduct'[Valid use case_catalog P/F]),'DataProduct'[Valid use case_catalog P/F] = \"Pass\")+0",
              "RETURN",
              "c1+c2+c3+c5"
            ],
            "formatString": "0",
            "lineageTag": "9a73f50a-95ec-4eab-84d6-ba5b3e2f0f54"
          },
          {
            "name": "1c4",
            "expression": "CALCULATE(COUNT('DataProduct'[Owner_catalog P/F]),'DataProduct'[Owner_catalog P/F] = \"Pass\")+0",
            "formatString": "0",
            "lineageTag": "538807c9-76df-4838-9b63-bf2647439f9c"
          }
        ],
        "partitions": [
          {
            "name": "DataProduct",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataProduct\" = Source{[Schema= DATABASE_SCHEMA,Item=\"DataProduct\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataProduct\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DataProductContactAssociation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f9228209-a9f2-48ef-bd76-3a4b3855747e",
            "sourceColumn": "DataProductId",
            "summarizeBy": "none"
          },
          {
            "name": "ContactRole",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f30a787a-b0a5-4e9b-99ca-c1c96923f277",
            "sourceColumn": "ContactRole",
            "summarizeBy": "none"
          },
          {
            "name": "ContactId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e30b29de-81e2-429f-abf9-eb516ac36939",
            "sourceColumn": "ContactId",
            "summarizeBy": "none"
          },
          {
            "name": "IsActive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "2e75d796-5478-4789-97c4-9f30ecb44d5d",
            "sourceColumn": "IsActive",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "31236631-10ef-425d-ad3a-df87513dc736",
        "partitions": [
          {
            "name": "DataProductContactAssociation",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataProductContactAssociation\" = Source{[Schema= DATABASE_SCHEMA,Item=\"DataProductContactAssociation\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataProductContactAssociation\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DataProductDataAssetAssociation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6a82698-29c5-4e57-ab24-4276fd4c8e03",
            "sourceColumn": "DataProductId",
            "summarizeBy": "none"
          },
          {
            "name": "DataAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab4f9105-383a-4b7e-a4bb-fbc40e175c00",
            "sourceColumn": "DataAssetId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "85660211-deff-4cb3-963f-ed539531d13e",
        "partitions": [
          {
            "name": "DataProductDataAssetAssociation",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataProductDataAssetAssociation\" = Source{[Schema= DATABASE_SCHEMA,Item=\"DataProductDataAssetAssociation\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataProductDataAssetAssociation\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "GlossaryTerm",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TermId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "14e859c0-8d1f-4bd1-8146-be3ae4bf8a77",
            "sourceColumn": "TermId",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2c7d032-6498-42bb-969f-0116c9f20f57",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "77f893c4-b69a-42db-9e95-38e9a1c8a28e",
            "sourceColumn": "CreatedAt",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f9a348bf-7047-4a26-b7dd-6a3c6cefe972",
            "sourceColumn": "ModifiedAt",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "036fe1e4-6b84-448f-a18c-4f78b720fc7c",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d0d90a8c-f95f-49bc-90d4-4a016e6aea1c",
            "sourceColumn": "LastRefreshedAt",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "01de9a54-60f5-4435-a357-dfa5c8d72f9c",
            "sourceColumn": "CreatedBy",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "89655635-74a3-4199-962d-1e3dd2376f3b",
            "sourceColumn": "ModifiedBy",
            "summarizeBy": "none"
          },
          {
            "name": "HasDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "b3d3da49-29fc-4bc5-b59b-354f9b12dea0",
            "sourceColumn": "HasDescription",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "11eca4bc-37b7-4418-8fab-8a61765a65a3",
        "partitions": [
          {
            "name": "GlossaryTerm",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_GlossaryTerm\" = Source{[Schema= DATABASE_SCHEMA,Item=\"GlossaryTerm\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_GlossaryTerm\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BusinessDomainDataProductAssociation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "82aec21e-2fc3-4feb-9de9-cb27d7d60b85",
            "sourceColumn": "DataProductId",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "31d95a76-065c-41f2-9c8a-a0af3fb3376a",
            "sourceColumn": "BusinessDomainId",
            "summarizeBy": "none"
          },
          {
            "name": "IsPrimaryDataProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "77ce2fd1-dc06-4986-a76c-39943bdb7695",
            "sourceColumn": "IsPrimaryDataProduct",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5f2992b4-bbe7-4efe-87a5-c806188552cd",
        "partitions": [
          {
            "name": "BusinessDomainDataProductAssociation",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomainDataProductAssociation\" = Source{[Schema= DATABASE_SCHEMA,Item=\"BusinessDomainDataProductAssociation\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomainDataProductAssociation\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "AssetURLTable",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "30837126-41ed-462f-939f-cdc00c960993",
            "sourceColumn": "DataProductId",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "aa401f1b-7db5-4011-a573-99d6d054dd13",
            "sourceColumn": "BusinessDomainId",
            "summarizeBy": "none"
          },
          {
            "name": "IsPrimaryDataProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "2a0bbd88-06c4-4644-ab26-7d0721f5e531",
            "sourceColumn": "IsPrimaryDataProduct",
            "summarizeBy": "none"
          },
          {
            "name": "DataAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "30ae45dd-59e6-4e33-bc1b-1efce4ca13fb",
            "sourceColumn": "DataAssetId",
            "summarizeBy": "none"
          },
          {
            "name": "Asset link",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "\"https://df.purview.microsoft.com/datacatalog/governance/main/catalog/dataProducts/dataAssetDetail?tid=\"& 'AccountInfo'",
              "\"&feature.tier=RC&dataAssetId=\"&'AssetURLTable'[DataAssetId]&",
              " \"&sourceDataProductId=\"& AssetURLTable[DataProductId]"
            ],
            "isHidden": true,
            "lineageTag": "d608b6c8-75c3-466a-96fd-dfe5cce1f8b6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "isHidden": true,
        "lineageTag": "1639e4c0-750f-43a3-8f2b-1074ddd39421",
        "partitions": [
          {
            "name": "AssetURLTable",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomainDataProductAssociation\" = Source{[Schema= DATABASE_SCHEMA,Item=\"BusinessDomainDataProductAssociation\"]}[Data],",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomainDataProductAssociation\", {\"DataProductId\"}, DataProductDataAssetAssociation, {\"DataProductId\"}, \"DataProductDataAssetAssociation\", JoinKind.Inner),",
                "    #\"Expanded DataProductDataAssetAssociation\" = Table.ExpandTableColumn(#\"Merged Queries\", \"DataProductDataAssetAssociation\", {\"DataAssetId\"}, {\"DataAssetId\"})",
                "in",
                "    #\"Expanded DataProductDataAssetAssociation\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "AccountInfo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TenantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32e21685-22eb-47ae-8621-6d4b68a0a469",
            "sourceColumn": "TenantID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ad76777b-f72a-4a5b-898b-edb5ce69c480",
        "partitions": [
          {
            "name": "AccountInfo",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #table({\"TenantID\"},{{#\"TENANT_ID\"}})",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DATABASE_SCHEMA",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "columns": [
          {
            "name": "DATABASE_SCHEMA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82cf0ed9-dfd4-4add-90f0-b26f13e453bd",
            "sourceColumn": "DATABASE_SCHEMA",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4ba41ebe-be7a-456f-804b-e15425e3986e",
        "partitions": [
          {
            "name": "DATABASE_SCHEMA",
            "mode": "import",
            "source": {
              "expression": "\"ecf09339-34e0-464b-a8fb-661209048543\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}