{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SERVER\",\"DATABASE\",\"DATABASE_SCHEMA\",\"BusinessDomain\",\"BusinessDomainTrends\",\"DataAsset\",\"DataProduct\",\"DataProductDataAssetAssociation\",\"BusinessDomainDataProductAssociation\",\"TENANT_ID\",\"AccountInfo\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1826.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "businessdomain.businessdomaindisplayname": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "BusinessDomain",
                    "ConceptualProperty": "BusinessDomainDisplayName"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Business domain name": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "businessdomain.businessdomainid": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "BusinessDomain",
                    "ConceptualProperty": "BusinessDomainId"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    ".": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "businessdomaintrends.trend_metadata_completeness": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "BusinessDomainTrends",
                    "ConceptualProperty": "Trend_Metadata completeness"
                  }
                },
                "State": "Generated"
              },
              "businessdomaintrends.trend_overall_health_score": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "BusinessDomainTrends",
                    "ConceptualProperty": "Trend_Overall health score"
                  }
                },
                "State": "Generated"
              },
              "businessdomaintrends.trend_quality": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "BusinessDomainTrends",
                    "ConceptualProperty": "Trend_Quality"
                  }
                },
                "State": "Generated"
              },
              "businessdomaintrends.trend_use": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "BusinessDomainTrends",
                    "ConceptualProperty": "Trend_Use"
                  }
                },
                "State": "Generated"
              },
              "dataasset.displayname": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataAsset",
                    "ConceptualProperty": "DisplayName"
                  }
                },
                "State": "Generated"
              },
              "dataproduct.action_item_measure": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "Action item measure"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Action items": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.action_items": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "Action Items"
                  }
                },
                "State": "Generated"
              },
              "dataproduct.asset_count": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "Asset count"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Asset count": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.asset_count_check": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "Asset count check"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Asset count check": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.c2_ownership": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "C2_Ownership"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Ownership": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.c3_authoritative_source": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "C3_Authoritative source"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Authoritative source": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.c5_catalog": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "C5_Catalog"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Catalog": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.c6_classification": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "C6_Classification"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Classification": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.c7_access_entitlement": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "C7_Access entitlement"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Access entitlement": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.c8_data_consumption_purpose": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "C8_Data consumption purpose"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Data consumption purpose": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.c_12_data_quality": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "C_12 Data quality"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Data quality": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.classification_check": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "classification Check"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Classification check": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.column1c2_ownership": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "1C2_Ownership"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Ownership": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.column1c5_catalog": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "1C5_Catalog"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Catalog": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.column1c6_classification": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "1C6_Classification"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Classification": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.column1metadata_completeness": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "1Metadata completeness"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Metadata completeness": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.column1overall_health_score": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "1Overall health score"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Overall health score": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.dataproductdisplayname": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "DataProductDisplayName"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Data product name": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.dataproductid": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "DataProductId"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    ".": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.glossaryterm_check": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "GlossaryTerm check"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Glossary term check": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.overall_health_score": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "Overall health score"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Governance score": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.ownership_check": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "Ownership check"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Ownership Check": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.total_assets": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataAsset",
                    "ConceptualProperty": "Asset count"
                  }
                },
                "State": "Generated"
              },
              "dataproduct.total_dataproducts": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "Total DataProducts"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Data products": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "dataproduct.validusecase_check": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DataProduct",
                    "ConceptualProperty": "ValidUseCase check"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Valid usecase check": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "SERVER",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"dghdogfoodsynapse-ondemand.sql.azuresynapse.net\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a14b6f22-ea8d-4a8e-97f2-05710f062eb1"
      },
      {
        "name": "DATABASE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"health_1\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "953805ba-bf53-4776-ad5b-7ae663b34473"
      },
      {
        "name": "TENANT_ID",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"12d98746-0b5a-4778-8bd0-449994469062\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "17e0cb58-b472-4281-a56f-7015df8fa2d7"
      },
      {
        "name": "DATABASE_SCHEMA",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"ecf09339-34e0-464b-a8fb-661209048543\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "912adbe7-d5db-4948-ab71-8d07ab39b3f9"
      }
    ],
    "relationships": [
      {
        "name": "e9b6f76b-5739-4f0f-895b-d3fb38551e94",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DataAssetId",
        "fromTable": "DataProductDataAssetAssociation",
        "toColumn": "DataAssetId",
        "toTable": "DataAsset"
      },
      {
        "name": "f704051b-1942-49b7-ae30-9bf8c1b491a2",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "BusinessDomainId",
        "fromTable": "BusinessDomainDataProductAssociation",
        "toColumn": "BusinessDomainId",
        "toTable": "BusinessDomain"
      },
      {
        "name": "07041328-47fa-4318-befc-74c5d3d34b4b",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DataProductId",
        "fromTable": "BusinessDomainDataProductAssociation",
        "toColumn": "DataProductId",
        "toTable": "DataProduct"
      },
      {
        "name": "a39ef729-2770-4609-b87d-2c7a7677f9ae",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DataProductId",
        "fromTable": "DataProductDataAssetAssociation",
        "toCardinality": "many",
        "toColumn": "DataProductId",
        "toTable": "BusinessDomainDataProductAssociation"
      },
      {
        "name": "6234c35b-8a28-c424-6d81-0bed833431dd",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "BusinessDomainId",
        "fromTable": "BusinessDomainTrends",
        "toColumn": "BusinessDomainId",
        "toTable": "BusinessDomain"
      },
      {
        "name": "00805423-4acb-4141-8ef1-a29561ddcfc3",
        "fromColumn": "CreatedAt",
        "fromTable": "BusinessDomain",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1a781283-4229-4adc-b73f-44c01b57a237"
      },
      {
        "name": "22e34acd-ddab-431d-8f0b-cd13b6b81055",
        "fromColumn": "ModifiedAt",
        "fromTable": "BusinessDomain",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e10937e5-1565-4815-a893-0cb38d197e1d"
      },
      {
        "name": "fc8639e1-ffde-4637-93a4-b77834e4405c",
        "fromColumn": "LastRefreshedAt",
        "fromTable": "BusinessDomain",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bf07079e-7d93-4615-9d40-6645a046cbb1"
      },
      {
        "name": "ba3169f2-f41e-4343-b3b4-2f83727a7002",
        "fromColumn": "LastRefreshedAt",
        "fromTable": "BusinessDomainTrends",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f131eda2-0aca-4b68-b3d5-c0294d9c91b9"
      },
      {
        "name": "b5d6823d-06f3-444a-93b4-0560680664b2",
        "fromColumn": "Date",
        "fromTable": "BusinessDomainTrends",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f82869d4-3d7a-42c6-ab8a-63d24cacffef"
      },
      {
        "name": "ba990456-8809-435b-a647-d68ff72d157e",
        "fromColumn": "CreatedAt",
        "fromTable": "DataAsset",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f2f409b3-7974-42ec-9085-79b92fdb4512"
      },
      {
        "name": "94241fda-545d-42f7-ac70-2294d699c3ee",
        "fromColumn": "ModifiedAt",
        "fromTable": "DataAsset",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_dc5105f7-f7ce-4920-b48f-69b004eb5475"
      },
      {
        "name": "df96fafe-6c5d-485b-9d81-47db65115d36",
        "fromColumn": "LastRefreshedAt",
        "fromTable": "DataAsset",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_73e8efaf-35c9-4c93-b507-e5feca1c6f31"
      },
      {
        "name": "c5bc9045-0ec9-4349-abc4-cca8b0f7394e",
        "fromColumn": "CreatedAt",
        "fromTable": "DataProduct",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c5729d02-5865-4ccf-982c-f06355c7ef59"
      },
      {
        "name": "dd755667-0976-4e08-8032-d6397d2ea0ec",
        "fromColumn": "ModifiedAt",
        "fromTable": "DataProduct",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d051808b-15ef-4bf6-9e9d-f5058ce87f03"
      },
      {
        "name": "9bd34984-882c-4096-898e-55b3bc5da279",
        "fromColumn": "LastRefreshedAt",
        "fromTable": "DataProduct",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bdccc7ef-9651-46a6-b933-f2709936cb95"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "BusinessDomain",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "212cb632-0b48-471f-a1aa-3a469eb3c09e",
            "sourceColumn": "BusinessDomainId",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainDisplayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "75f3b3b2-2ba0-40a1-a99e-53c5bd3c871c",
            "sourceColumn": "BusinessDomainDisplayName",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "08c01862-e173-4e62-b69a-ed5c8879aad9",
            "sourceColumn": "CreatedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_1a781283-4229-4adc-b73f-44c01b57a237"
                },
                "isDefault": true,
                "relationship": "00805423-4acb-4141-8ef1-a29561ddcfc3"
              }
            ]
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "3beb56d3-32d6-43f0-aa47-92e94d8c9057",
            "sourceColumn": "CreatedBy",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "a4bb3cea-6aa4-44e6-96d8-2c99ee9a77f0",
            "sourceColumn": "ModifiedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_e10937e5-1565-4815-a893-0cb38d197e1d"
                },
                "isDefault": true,
                "relationship": "22e34acd-ddab-431d-8f0b-cd13b6b81055"
              }
            ]
          },
          {
            "name": "ModifiedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "2121ab79-072d-4384-8f6c-91425126e0e7",
            "sourceColumn": "ModifiedBy",
            "summarizeBy": "none"
          },
          {
            "name": "GlossaryTermCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3907d87a-7141-407c-977b-6949beb885e8",
            "sourceColumn": "GlossaryTermCount",
            "summarizeBy": "sum"
          },
          {
            "name": "DataProductCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "425f02e6-9961-4222-982c-280454a68013",
            "sourceColumn": "DataProductCount",
            "summarizeBy": "sum"
          },
          {
            "name": "IsRootDomain",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "8e39a308-b872-4700-8e7d-ce9bfa97f261",
            "sourceColumn": "IsRootDomain",
            "summarizeBy": "none"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "1540c7e8-9007-48e8-a2e2-f9948f52e22f",
            "sourceColumn": "LastRefreshedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bf07079e-7d93-4615-9d40-6645a046cbb1"
                },
                "isDefault": true,
                "relationship": "fc8639e1-ffde-4637-93a4-b77834e4405c"
              }
            ]
          },
          {
            "name": "HasValidOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "d623da40-2e4e-43dc-af07-50e0e3e293b7",
            "sourceColumn": "HasValidOwner",
            "summarizeBy": "none"
          },
          {
            "name": "HasDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "98e0d34a-2072-4c16-9174-d3ce094482d1",
            "sourceColumn": "HasDescription",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bb22e2b4-7b67-4278-bc82-0426adf76ee0",
        "partitions": [
          {
            "name": "BusinessDomain",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomain\" = Source{[Schema= DATABASE_SCHEMA,Item=\"BusinessDomain\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomain\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BusinessDomainTrends",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "BusinessDomainTrendId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "06c090aa-0a25-4ca5-99a5-717053f799a8",
            "sourceColumn": "BusinessDomainTrendId",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "33b8338e-8f90-4470-934a-8586ee981f19",
            "sourceColumn": "BusinessDomainId",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b1b99c18-c54f-46d4-958a-5b57c1721e72",
            "sourceColumn": "DataProductCount",
            "summarizeBy": "sum"
          },
          {
            "name": "AssetCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "48b4dd73-0802-4cec-b32b-4e5ab3d6ef2e",
            "sourceColumn": "AssetCount",
            "summarizeBy": "sum"
          },
          {
            "name": "ClassificationPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e913fd3-503b-49f8-a31b-21cb5004f942",
            "sourceColumn": "ClassificationPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "GlossaryTermPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a55ec180-4a5b-47ce-a84b-685395c2506c",
            "sourceColumn": "GlossaryTermPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "DataQualityScorePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e9d8d89d-e181-4113-b068-30818381efee",
            "sourceColumn": "DataQualityScorePassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "ValidDataProductOwnerPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1fd02d44-f020-4ff8-a0f6-9504390d2e80",
            "sourceColumn": "ValidDataProductOwnerPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "DataShareAgreementSetOrExemptPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d8f00ed5-d02b-43b6-805f-376b7395c218",
            "sourceColumn": "DataShareAgreementSetOrExemptPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "ValidUseCasePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "728b37aa-9a06-426f-89c6-26541f15ee1b",
            "sourceColumn": "ValidUseCasePassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "ValidTermsOfUsePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "55f542c4-287f-49ed-bb62-fc70817b339c",
            "sourceColumn": "ValidTermsOfUsePassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "AccessEntitlementPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9fb4438e-0e01-4aad-8185-c9edb551f680",
            "sourceColumn": "AccessEntitlementPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm d\\, yyyy",
            "lineageTag": "50bf2db3-bef9-454d-9c9d-7557b81b5469",
            "sourceColumn": "LastRefreshedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f131eda2-0aca-4b68-b3d5-c0294d9c91b9"
                },
                "isDefault": true,
                "relationship": "ba3169f2-f41e-4343-b3b4-2f83727a7002"
              }
            ]
          },
          {
            "name": "TotalOpenActionsCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3e8afa3-9a47-4d1e-b09d-80363a87d37d",
            "sourceColumn": "TotalOpenActionsCount",
            "summarizeBy": "sum"
          },
          {
            "name": "DataProductDescriptionPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3897a97-3cad-4ad7-b375-f5bd0d9ead19",
            "sourceColumn": "DataProductDescriptionPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "AuthoritativeSourcePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6f5c36bc-d55b-48ad-9959-614d21bd9899",
            "sourceColumn": "AuthoritativeSourcePassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm d\\, yyyy",
            "lineageTag": "a4586e51-3a33-42fb-beaa-5e2fafbd4552",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f82869d4-3d7a-42c6-ab8a-63d24cacffef"
                },
                "isDefault": true,
                "relationship": "b5d6823d-06f3-444a-93b4-0560680664b2"
              }
            ]
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "91ac7ecd-d41a-4a53-8173-65b4983ce7b8",
            "sourceColumn": "Time",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d6ae76ed-5409-4399-b782-f93c0a38a783",
        "measures": [
          {
            "name": "Trend_Metadata completeness",
            "expression": "DIVIDE(BusinessDomainTrends[Trend_Metadata completeness pass count],SUM(BusinessDomainTrends[DataProductCount]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c0b8c886-486a-4d4c-bdf6-7f7d6d88ce16"
          },
          {
            "name": "Trend_Metadata completeness pass count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "(SUM('BusinessDomainTrends'[ClassificationPassCount])+",
              "SUM('BusinessDomainTrends'[ValidDataProductOwnerPassCount])+SUM(BusinessDomainTrends[DataProductDescriptionPassCount])+SUM(BusinessDomainTrends[GlossaryTermPassCount])+SUM(BusinessDomainTrends[ValidUseCasePassCount])+SUMX(BusinessDomainTrends,BusinessDomainTrends[Trend_Asset Pass count])",
              ")/6"
            ],
            "lineageTag": "2b5906bd-a5fa-477e-a8f6-f66845f465d6"
          },
          {
            "name": "Trend_Quality pass count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "(SUM('BusinessDomainTrends'[DataQualityScorePassCount])+",
              "SUM('BusinessDomainTrends'[AuthoritativeSourcePassCount]))/2"
            ],
            "lineageTag": "0f014697-4f30-475a-898a-63e0938a2523"
          },
          {
            "name": "Trend_Use pass count",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "(sum('BusinessDomainTrends'[DataShareAgreementSetOrExemptPassCount])+",
              "sum('BusinessDomainTrends'[AccessEntitlementPassCount]))/2"
            ],
            "lineageTag": "e0e00cf1-4194-410e-a800-7e49ec4530e1"
          },
          {
            "name": "Trend_Sum of all metrics",
            "expression": [
              "",
              "SUM(BusinessDomainTrends[ValidDataProductOwnerPassCount])+",
              "SUM(BusinessDomainTrends[ClassificationPassCount])+",
              "//SUM(BusinessDomainTrends[DataQualityScorePassCount])+",
              "//SUM(BusinessDomainTrends[AuthoritativeSourcePassCount])+",
              "//SUM(BusinessDomainTrends[AccessEntitlementPassCount])+",
              "//SUM(BusinessDomainTrends[DataShareAgreementSetOrExemptPassCount])+",
              "SUM(BusinessDomainTrends[DataProductDescriptionPassCount])+",
              "SUM(BusinessDomainTrends[GlossaryTermPassCount])+",
              "SUM(BusinessDomainTrends[ValidUseCasePassCount])+",
              "SUMX(BusinessDomainTrends,BusinessDomainTrends[Trend_Asset Pass count])",
              "",
              ""
            ],
            "formatString": "0",
            "lineageTag": "f7e9d30f-be49-464c-bf16-670acb4219e8"
          },
          {
            "name": "Trend_Overall health score",
            "expression": "DIVIDE([Trend_Sum of all metrics],SUM('BusinessDomainTrends'[DataProductCount])*10)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "fa4abfc3-413d-4229-b8df-134e07c870c7"
          },
          {
            "name": "Trend_Quality",
            "expression": "DIVIDE([Trend_Quality pass count],sum('BusinessDomainTrends'[DataProductCount]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "bba3ffdc-bccc-4086-9755-0fe4eca2ec02"
          },
          {
            "name": "Trend_Use",
            "expression": "DIVIDE([Trend_Use pass count],sum('BusinessDomainTrends'[DataProductCount]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5c59a53d-e2d1-42ed-a0c5-8e3953391799"
          },
          {
            "name": "Trend_Asset Pass count",
            "expression": "CALCULATE(COUNT('DataProduct'[DataProductId]),DataProduct[AssetCount] > 0)",
            "formatString": "0",
            "lineageTag": "f539233d-7090-4b2c-bd5a-b10780f26066"
          }
        ],
        "partitions": [
          {
            "name": "BusinessDomainTrends",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomainTrends\" = Source{[Schema=DATABASE_SCHEMA,Item=\"BusinessDomainTrends\"]}[Data],",
                "    #\"Duplicated Column\" = Table.DuplicateColumn(#\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomainTrends\", \"LastRefreshedAt\", \"LastRefreshedAt - Copy\"),",
                "    #\"Split Column by Delimiter\" = Table.SplitColumn(Table.TransformColumnTypes(#\"Duplicated Column\", {{\"LastRefreshedAt - Copy\", type text}}, \"en-US\"), \"LastRefreshedAt - Copy\", Splitter.SplitTextByEachDelimiter({\" \"}, QuoteStyle.Csv, false), {\"LastRefreshedAt - Copy.1\", \"LastRefreshedAt - Copy.2\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Split Column by Delimiter\",{{\"LastRefreshedAt - Copy.1\", type date}, {\"LastRefreshedAt - Copy.2\", type time}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"LastRefreshedAt - Copy.1\", \"Date\"}, {\"LastRefreshedAt - Copy.2\", \"Time\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DataAsset",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DataAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e39026af-ff1f-434e-9062-5b5c98fb7a68",
            "sourceColumn": "DataAssetId",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "f1e9149d-ec74-4fce-a79e-70964e721c76",
            "sourceColumn": "CreatedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f2f409b3-7974-42ec-9085-79b92fdb4512"
                },
                "isDefault": true,
                "relationship": "ba990456-8809-435b-a647-d68ff72d157e"
              }
            ]
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "91eb7a17-9539-4015-8baa-91f543df2229",
            "sourceColumn": "CreatedBy",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f7de614-5aa1-40e8-be9b-eb3e96afaab5",
            "sourceColumn": "ModifiedBy",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "40711738-1686-471a-acda-9ca6c8d7b098",
            "sourceColumn": "ModifiedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_dc5105f7-f7ce-4920-b48f-69b004eb5475"
                },
                "isDefault": true,
                "relationship": "94241fda-545d-42f7-ac70-2294d699c3ee"
              }
            ]
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "d96ae37b-f12a-43e7-84af-41f6f2908812",
            "sourceColumn": "LastRefreshedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_73e8efaf-35c9-4c93-b507-e5feca1c6f31"
                },
                "isDefault": true,
                "relationship": "df96fafe-6c5d-485b-9d81-47db65115d36"
              }
            ]
          },
          {
            "name": "SourceType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "742cc15a-4dc4-4d9e-9b76-c5603dddb9ac",
            "sourceColumn": "SourceType",
            "summarizeBy": "none"
          },
          {
            "name": "ObjectType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0fad8f6-34aa-4c3d-a885-3a133b725801",
            "sourceColumn": "ObjectType",
            "summarizeBy": "none"
          },
          {
            "name": "HasSchema",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "5f1f365b-63fe-4264-8e64-8f2e8b0ca6d8",
            "sourceColumn": "HasSchema",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b33a5eff-5c11-4283-a558-03b47eaa9275",
            "sourceColumn": "BusinessDomainId",
            "summarizeBy": "none"
          },
          {
            "name": "SourceAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "917b9909-257f-4aba-b87e-af54d4c6d5d3",
            "sourceColumn": "SourceAssetId",
            "summarizeBy": "none"
          },
          {
            "name": "DisplayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ae23736-3006-4d6c-afa3-1d6061bed88b",
            "sourceColumn": "DisplayName",
            "summarizeBy": "none"
          },
          {
            "name": "HasClassification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c73d33cd-137a-4338-87f0-0390894a06de",
            "sourceColumn": "HasClassification",
            "summarizeBy": "none"
          },
          {
            "name": "HasDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "cec1fb47-ccff-4e66-8e4c-735d5bae6563",
            "sourceColumn": "HasDescription",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e01a6210-45a2-498b-a38a-192cae8264e8",
        "measures": [
          {
            "name": "Asset count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DISTINCTCOUNT(DataAsset[DataAssetId])",
            "formatString": "0",
            "lineageTag": "ac7da6b6-b54c-4b0d-97bc-443dfff75361"
          }
        ],
        "partitions": [
          {
            "name": "DataAsset",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataAsset\" = Source{[Schema= DATABASE_SCHEMA,Item=\"DataAsset\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataAsset\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DataProduct",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "db0c9ab9-0f2d-4fed-8b70-b2279dac8c4f",
            "sourceColumn": "DataProductId",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductDisplayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a39dbf37-4089-4f07-9552-4da49c3b6fa4",
            "sourceColumn": "DataProductDisplayName",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f618f6d-0ac1-4f60-be42-32cf40567a53",
            "sourceColumn": "DataProductType",
            "summarizeBy": "none"
          },
          {
            "name": "HasValidOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "df42f1c6-5b80-4516-8bf4-e96394cb19cd",
            "sourceColumn": "HasValidOwner",
            "summarizeBy": "none"
          },
          {
            "name": "HasValidUseCase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ad4067cc-72a9-4c38-a947-45a17093c2e7",
            "sourceColumn": "HasValidUseCase",
            "summarizeBy": "none"
          },
          {
            "name": "AssetCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "26f5dc91-2a0f-4962-9798-ce1088adf767",
            "sourceColumn": "AssetCount",
            "summarizeBy": "sum"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "ae87c72b-772c-4500-9c27-b6b2c94fe6c0",
            "sourceColumn": "CreatedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c5729d02-5865-4ccf-982c-f06355c7ef59"
                },
                "isDefault": true,
                "relationship": "c5bc9045-0ec9-4349-abc4-cca8b0f7394e"
              }
            ]
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8dd7633-e73e-46bd-9571-6a4c7e1d361d",
            "sourceColumn": "CreatedBy",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "0b0cabc2-f4a3-463a-ae80-93532959cbab",
            "sourceColumn": "ModifiedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d051808b-15ef-4bf6-9e9d-f5058ce87f03"
                },
                "isDefault": true,
                "relationship": "dd755667-0976-4e08-8032-d6397d2ea0ec"
              }
            ]
          },
          {
            "name": "ModifiedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "5707fdc7-b70b-41f4-91a2-c96f61b6b2f1",
            "sourceColumn": "ModifiedBy",
            "summarizeBy": "none"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "cee8dcaf-70f8-47bf-a718-f7ad440326ac",
            "sourceColumn": "LastRefreshedAt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bdccc7ef-9651-46a6-b933-f2709936cb95"
                },
                "isDefault": true,
                "relationship": "9bd34984-882c-4096-898e-55b3bc5da279"
              }
            ]
          },
          {
            "name": "IsAuthoritativeSource",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "cea7db2f-53b8-4e69-acb3-fd6b1649028d",
            "sourceColumn": "IsAuthoritativeSource",
            "summarizeBy": "none"
          },
          {
            "name": "HasDataQualityScore",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0ab26c16-e9bf-4c61-8e4d-f486721fd7f4",
            "sourceColumn": "HasDataQualityScore",
            "summarizeBy": "none"
          },
          {
            "name": "ClassificationPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8a126b99-65c8-4d6d-b958-ea8d100c1eba",
            "sourceColumn": "ClassificationPassCount",
            "summarizeBy": "sum"
          },
          {
            "name": "HasAccessEntitlement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "c59ed45b-910b-4e22-b602-d694829cdf81",
            "sourceColumn": "HasAccessEntitlement",
            "summarizeBy": "none"
          },
          {
            "name": "HasDataShareAgreementSetOrExempt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "79ad4ed1-5623-40f6-8aa7-ad0cbe8e95c0",
            "sourceColumn": "HasDataShareAgreementSetOrExempt",
            "summarizeBy": "none"
          },
          {
            "name": "GlossaryTermCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4a8c05c3-f5c0-4fd9-9d4d-c75e6fd2a351",
            "sourceColumn": "GlossaryTermCount",
            "summarizeBy": "sum"
          },
          {
            "name": "Access entitlement P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF('DataProduct'[HasAccessEntitlement] = TRUE(),\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "6c0ec664-d767-456c-b0e1-0a53e842f4ad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Action Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "expression": [
              "IF(",
              "                'DataProduct'[Owner P/F]= \"Fail\",1,0)",
              "                +IF('DataProduct'[Classification_Product P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Assetcount_catalog P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Glosssary Term count_catalog P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Description_catalog P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Valid use case_catalog P/F] = \"Fail\",1,0)",
              "               /* +IF('DataProduct'[Data Qualiy P/F] = \"Fail\", 1,0)",
              "                +IF('DataProduct'[Authoritative source P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Access entitlement P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Data consumption purpse P/F] = \"Fail\",1,0",
              "                )*/"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "2c87178d-3fa0-4f0d-9307-8a5c201c25f5",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Authoritative source P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF('DataProduct'[IsAuthoritativeSource]= TRUE(),\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "91d8f8a6-65af-4f4b-95a4-19b3bb8a1f57",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Classification_Product P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(COALESCE('DataProduct'[ClassificationPassCount],0) > 0 , \"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "76d2386b-502f-4748-8ea5-5fa921ae906e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Data consumption purpse P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF('DataProduct'[HasDataShareAgreementSetOrExempt] = TRUE(), \"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "ba828d2a-4632-4b29-896c-d8f6e0d8cd47",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Data Qualiy P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF('DataProduct'[HasDataQualityScore] = TRUE() ,\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "9811b820-10ba-44d4-b769-3f6304e5d90a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Overall health staus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Overall health score] >= [Max_Thresh hold], \"Healthy\", ",
              "                            [Overall health score] >= [Min_Thresh hold] && [Overall health score] <[Max_Thresh hold] , \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "7314c5a9-fc97-430a-bc17-e2a197b06216",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Owner P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF('DataProduct'[HasValidOwner] = TRUE(), \"Pass\", \"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "1116f6a1-d103-4170-bd5b-e588adb8cd8e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Valid use case_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(COALESCE('DataProduct'[HasValidUseCase],0) = TRUE() , \"Pass\", \"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "139fa52e-a368-4695-93c7-436fab867a0f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Assetcount_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(COALESCE('DataProduct'[AssetCount],0) >= 1,\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "239fc81e-0ed9-4c93-91be-4b1f38cce209",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Description_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(COALESCE('DataProduct'[HasDescription],0) = TRUE(),\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "46edeabd-ad87-4538-ad4b-c9c6d0498c79",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Glosssary Term count_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "expression": "IF(COALESCE('DataProduct'[GlossaryTermCount],0) > 0 ,\"Pass\",\"Fail\")",
            "isDataTypeInferred": true,
            "lineageTag": "57cd768e-7c5e-4485-a4d2-55926428d5e9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "HasDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "f02d5487-6225-4e9b-a0c9-b38067c34ce8",
            "sourceColumn": "HasDescription",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e8f44bf-9d58-4d66-9c63-391fccaaa750",
            "sourceColumn": "DataProductStatus",
            "summarizeBy": "none"
          },
          {
            "name": "HasValidTermsOfUse",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "0ea5692f-10b8-4d07-8843-fa94aae7f127",
            "sourceColumn": "HasValidTermsOfUse",
            "summarizeBy": "none"
          },
          {
            "name": "Catalog Action Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "IF('DataProduct'[Assetcount_catalog P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Glosssary Term count_catalog P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Description_catalog P/F] = \"Fail\",1,0)",
              "                +IF('DataProduct'[Valid use case_catalog P/F] = \"Fail\",1,0)"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "08bfa702-9ef0-4b53-a088-15e8c330a42f",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Classification Action Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF('DataProduct'[Classification_Product P/F] = \"Fail\",1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "c10b28a1-de49-465b-ad1c-b549aa66f742",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Ownership Action Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "IF('DataProduct'[Owner P/F]= \"Fail\",1,0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "3d3a7bf1-88c3-4cdc-a313-592de1db38c8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "classification Check",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": "IF(DataProduct[ClassificationPassCount]>0,1, 0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "8b027c2f-0697-4710-b5c2-9974e1dcac27",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Ownership check",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": "IF(DataProduct[HasValidOwner] = TRUE(),1, 0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "a09f7dd2-1592-478e-a3b1-e0d11de1bbda",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "ValidUseCase check",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": "IF(DataProduct[HasValidUseCase] = TRUE(),1, 0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "fbf60ce3-c257-4a69-a912-5541a9e0003b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "GlossaryTerm check",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": "IF(DataProduct[GlossaryTermCount]>0,1, 0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "4ef608eb-21c6-49a1-8629-c291d6c98133",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Description check",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": "IF(DataProduct[HasDescription] = TRUE(),1, 0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "87aa2ef1-01bc-45a9-96cf-221a2757174b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Asset count check",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": "IF(DataProduct[AssetCount]>0,1, 0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "de897616-5e32-42ca-b417-e1dbe486cf02",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Glossarytermcheck",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataType": "int64",
            "expression": "IF(DataProduct[GlossaryTermCount]>0,1, 0)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "eb72ae3a-0b27-408a-8023-4a326bce41a1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Action center link",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"https://purview.microsoft.com/datacatalog/governance/main/datashare/healthActions?tid=\" & LOWER(FIRSTNONBLANK(AccountInfo[TenantId], True())) ",
            "isDataTypeInferred": true,
            "lineageTag": "44cf55e8-27e1-4804-b075-0ff378ebe01a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "5e64d8f2-a51a-4abe-b8b8-86d5ed754fb7",
        "measures": [
          {
            "name": "Access entitlement health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C7_Access entitlement] > [Max_Thresh hold], \"Healthy\", ",
              "                            [C7_Access entitlement] > [Min_Thresh hold] && [C7_Access entitlement] <= [Max_Thresh hold] , \"Fair\",",
              "                            \"Not healthy\")"
            ],
            "lineageTag": "b7ffffc4-0719-43cb-a79d-53279abc5873"
          },
          {
            "name": "Access entitlement Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(COALESCE(DISTINCTCOUNT('DataProduct'[DataProductId]),0),",
              "'DataProduct'[HasAccessEntitlement] = TRUE())"
            ],
            "formatString": "0",
            "lineageTag": "40fa872f-835e-4679-9052-8f8547a37610"
          },
          {
            "name": "Access entitlement thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [C7_Access entitlement] > [Max_Thresh hold], \"#80D091\", ",
              "                            [C7_Access entitlement] >[Min_Thresh hold] && [C7_Access entitlement] <=[Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "ab5ad6bc-ff85-4d61-9b24-bd5c3772d3c2"
          },
          {
            "name": "Action item measure",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(sum('DataProduct'[Action Items]) = BLANK(),0,SUM('DataProduct'[Action Items]))",
            "formatString": "0",
            "lineageTag": "990c4ec0-d8bc-4f27-9879-86b4bce80455"
          },
          {
            "name": "Authoritative source health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C3_Authoritative source] > [Max_Thresh hold], \"Healthy\", ",
              "                            [C3_Authoritative source] >[Min_Thresh hold] && [C3_Authoritative source] <= 0.5 , \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "444d4604-3386-4cd4-846d-c320bf253902"
          },
          {
            "name": "Authoritative source Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(COALESCE(DISTINCTCOUNT('DataProduct'[DataProductId]),0),",
              "'DataProduct'[IsAuthoritativeSource] = TRUE())"
            ],
            "formatString": "0",
            "lineageTag": "887ea7f2-bcf9-4962-8f16-bc744e1906ca"
          },
          {
            "name": "Authoritative thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [C3_Authoritative source] > [Max_Thresh hold], \" #80D091\", ",
              "                            [C3_Authoritative source] > [Min_Thresh hold] && [C3_Authoritative source] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "359dfd36-0299-4bb5-b9d1-2e77a355652e"
          },
          {
            "name": "C_12 Data quality",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Data Quality Pass count],[Total DataProducts]) <>BLANK(),DIVIDE([Data Quality Pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "f315a253-ecdf-47db-bc8e-1c358c0d9030"
          },
          {
            "name": "C2_Ownership",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Owner Pass count],[Total DataProducts])<>BLANK(), DIVIDE([Owner Pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d0af49fd-f713-48b2-95ad-6d80adaabd97"
          },
          {
            "name": "C3_Authoritative source",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Authoritative source Pass count],[Total DataProducts]) <>BLANK(),DIVIDE([Authoritative source Pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5a5e09ab-0409-411f-a714-a3e844d3ef85"
          },
          {
            "name": "C5_Catalog",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE([Catalog Pass count]/4,[Total DataProducts])+0",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "566f3007-80ea-4c64-990d-790539da87d1"
          },
          {
            "name": "C6_Classification",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Classifiaction pass count],[Total DataProducts])<>BLANK(),DIVIDE([Classifiaction pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0057267d-3af5-4f98-a98b-c975fb2a8b03"
          },
          {
            "name": "C7_Access entitlement",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Access entitlement Pass count],[Total DataProducts])<>BLANK(),DIVIDE([Access entitlement Pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c41438bc-0a9a-46a9-af5d-11475af66d9a"
          },
          {
            "name": "C8_Data consumption purpose",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "IF(DIVIDE([Data consumption Purpose Pass count],[Total DataProducts])<>BLANK(),DIVIDE([Data consumption Purpose Pass count],[Total DataProducts]),0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "58960f74-44b3-4bd4-8ee0-df42002d83c1"
          },
          {
            "name": "Catalog health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C5_Catalog] >= [Max_Thresh hold], \"Healthy\", ",
              "                            [C5_Catalog] >= [Min_Thresh hold] && [C5_Catalog] <[Max_Thresh hold] , \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "2a781147-eb50-4ffd-8e3e-a8281d71e158"
          },
          {
            "name": "Catalog Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "var c1 = CALCULATE(COALESCE(DISTINCTCOUNT('DataProduct'[DataProductId]),0),",
              "'DataProduct'[AssetCount] > 0)",
              "var c2 = CALCULATE(COALESCE(DISTINCTCOUNT('DataProduct'[DataProductId]),0),",
              "'DataProduct'[GlossaryTermCount] >0)",
              "var c3 = CALCULATE(COALESCE(DISTINCTCOUNT('DataProduct'[DataProductId]),0),",
              "'DataProduct'[HasDescription] = TRUE())",
              "var c4 = CALCULATE(COALESCE(DISTINCTCOUNT('DataProduct'[DataProductId]),0),",
              "'DataProduct'[HasValidUseCase] = TRUE())",
              "RETURN",
              "c1+c2+c3+c4"
            ],
            "formatString": "0",
            "lineageTag": "799eeb76-a960-45bc-b976-1b177791ec26"
          },
          {
            "name": "Catalog thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [C5_Catalog] >= [Max_Thresh hold], \" #80D091\", ",
              "                            [C5_Catalog] >= [Min_Thresh hold] && [C5_Catalog] < [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "3bb0813d-0b95-41cb-8b4f-431a75220e91"
          },
          {
            "name": "Classifiaction pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(COALESCE(DISTINCTCOUNT('DataProduct'[DataProductId]),0),",
              "'DataProduct'[ClassificationPassCount] > 0) "
            ],
            "formatString": "0",
            "lineageTag": "88716b25-a863-4e04-82b3-6d65fd5d6a5e"
          },
          {
            "name": "Classification health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C6_Classification] >= [Max_Thresh hold], \"Healthy\", ",
              "                            [C6_Classification] >= [Min_Thresh hold]&& [C6_Classification] < [Max_Thresh hold], \"Fair\",",
              "                            \"Not healthy\")"
            ],
            "lineageTag": "e84628c8-ec41-4236-859e-21354ed88f44"
          },
          {
            "name": "Classification thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                           ",
              "                            [C6_Classification] >= [Max_Thresh hold], \" #80D091\", ",
              "                            [C6_Classification] >= [Min_Thresh hold] && [C6_Classification] < [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "836b6889-86bd-4a9a-bcb6-0ad1a4aac353"
          },
          {
            "name": "Data consumption health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C8_Data consumption purpose] >[Max_Thresh hold], \"Healthy\", ",
              "                            [C8_Data consumption purpose] >[Min_Thresh hold] && [C8_Data consumption purpose] <= [Max_Thresh hold], \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "dace400e-2202-4a1b-9219-705a20357aa3"
          },
          {
            "name": "Data consumption Purpose Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(COALESCE(DISTINCTCOUNT('DataProduct'[DataProductId]),0),",
              "'DataProduct'[HasDataShareAgreementSetOrExempt] = TRUE())"
            ],
            "formatString": "0",
            "lineageTag": "7855a0ec-41a3-4265-b313-0bf7207d60ca"
          },
          {
            "name": "Data consumption thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                           ",
              "                            [C8_Data consumption purpose] > [Max_Thresh hold], \" #80D091\", ",
              "                            [C8_Data consumption purpose] > [Min_Thresh hold] && [C8_Data consumption purpose] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "81caf6f8-0f01-4a0b-a430-909b617658e0"
          },
          {
            "name": "Data quality health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C_12 Data quality] >[Max_Thresh hold], \"Healthy\", ",
              "                            [C_12 Data quality] > [Min_Thresh hold] && [C_12 Data quality] <= [Max_Thresh hold], \"Fair\",",
              "                            \"Not healthy\")"
            ],
            "lineageTag": "416e646a-07c2-4fc1-bfe7-acee39ce095d"
          },
          {
            "name": "Data Quality Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(COALESCE(DISTINCTCOUNT('DataProduct'[DataProductId]),0),",
              "'DataProduct'[HasDataQualityScore] = TRUE())"
            ],
            "formatString": "0",
            "lineageTag": "8de7c777-329d-47d5-8454-a6299c3491a4"
          },
          {
            "name": "Data quality thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "",
              "                            [C_12 Data quality] > [Max_Thresh hold], \" #80D091\", ",
              "                            [C_12 Data quality] > [Min_Thresh hold] && [C_12 Data quality] <= [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "1bbf4b86-b8ab-409f-b8d7-5ae433350070"
          },
          {
            "name": "Target",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "0.5",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "bbf2d5af-8953-4ec0-8fcf-1047219c5f74"
          },
          {
            "name": "Max_Thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "0.8",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "9a461d76-b808-4fda-8d19-7b073bc50ee8"
          },
          {
            "name": "Metadata completeness",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "DIVIDE(([Owner Pass count]+[Catalog Pass count]+[Classifiaction pass count])/6,",
              "[Total DataProducts])+0"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dc3bd2a5-c74d-4898-9517-f75fbf05fe29"
          },
          {
            "name": "Metadata completeness status",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Metadata completeness] >= [Max_Thresh hold], \"Healthy\", ",
              "                            [Metadata completeness] >= [Min_Thresh hold] && [Metadata completeness] < [Max_Thresh hold] , \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "b4cb6f86-f8f9-49ee-9c09-f9bad0b250f7"
          },
          {
            "name": "Metadata completeness thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Metadata completeness] >= [Max_Thresh hold], \" #80D091\", ",
              "                            [Metadata completeness] >= [Min_Thresh hold] && [Metadata completeness] < [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "090cf046-3d2f-45ef-aa54-51b8fe474c28"
          },
          {
            "name": "Min_Thresh hold",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "0.5",
            "lineageTag": "e380079a-7aa7-45db-9608-733f7581af21"
          },
          {
            "name": "Overall health score",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "DIVIDE(calculate([C5_Catalog]+[C6_Classification]+[C2_Ownership]),3)",
              "",
              "///DIVIDE([Sum of Pass Metrics],[Total DataProducts]*6)+0"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "01d5ba84-97cc-4e95-9017-5e4f00782ca0"
          },
          {
            "name": "Overall health staus_measure",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Overall health score] >= [Max_Thresh hold], \"Healthy\", ",
              "                            [Overall health score] >= [Min_Thresh hold] && [Overall health score] < [Max_Thresh hold], \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "33398188-377a-4f82-a59c-b2033adfe038"
          },
          {
            "name": "Overall health thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                           ",
              "                            [Overall health score] >= [Max_Thresh hold], \" #80D091\", ",
              "                            [Overall health score] >= [Min_Thresh hold] && [Overall health score] < [Max_Thresh hold],\"#E8CC78\",",
              "                            ",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "bb297018-9b5e-4f7a-b5ea-f4ad72911b4a"
          },
          {
            "name": "Owner Pass count",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "CALCULATE(COALESCE(DISTINCTCOUNT('DataProduct'[DataProductId]),0),",
              "'DataProduct'[HasValidOwner] = TRUE())"
            ],
            "formatString": "0",
            "lineageTag": "d9c88924-6f6f-4069-9fcd-3ab22c711971"
          },
          {
            "name": "Ownership health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [C2_Ownership] >=[Max_Thresh hold], \"Healthy\", ",
              "                            [C2_Ownership] >= [Min_Thresh hold] && [C2_Ownership] <[Max_Thresh hold] , \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "a7988ff8-6a26-4a75-9e5f-9c989dd2227d"
          },
          {
            "name": "Ownership thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [C2_Ownership] >= [Max_Thresh hold], \" #80D091\", ",
              "                            [C2_Ownership] >= [Min_Thresh hold] && [C2_Ownership] < [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "14a55b68-dcfc-479a-acd4-5f9472bd377e"
          },
          {
            "name": "Quality",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE(([Authoritative source Pass count]+[Data Quality Pass count])/2,[Total DataProducts])+0",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "19a378de-e683-4eb8-9dd6-789066e5383a"
          },
          {
            "name": "Quality health staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Quality] > [Max_Thresh hold], \"Healthy\", ",
              "                            [Quality] > [Min_Thresh hold] && [Quality] <= [Max_Thresh hold] , \"Fair\",",
              "                            \"Not healthy\")"
            ],
            "lineageTag": "ac883693-c0ec-4efd-b2c1-0b2702982e90"
          },
          {
            "name": "Quality thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [Quality] >= [Max_Thresh hold], \" #80D091\", ",
              "                            [Quality] >= [Min_Thresh hold] && [Quality] < [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "e685dd30-db6a-4c37-9b1b-584a4af55873"
          },
          {
            "name": "Sum of Pass Metrics",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "[Owner Pass count]+",
              "[Catalog Pass count]+",
              "[Classifiaction pass count]",
              "//+[Data Quality Pass count]+",
              "//[Authoritative source Pass count]+",
              "//[Access entitlement Pass count]+",
              "//[Data consumption Purpose Pass count]"
            ],
            "formatString": "0",
            "lineageTag": "57d81210-f823-42ba-8773-d191d79199f8"
          },
          {
            "name": "Total DataProducts",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DISTINCTCOUNT('DataProduct'[DataProductId])+0",
            "formatString": "0",
            "lineageTag": "b8618123-5a08-4245-9b93-1fb72213875e"
          },
          {
            "name": "Total Domains",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DISTINCTCOUNT('BusinessDomain'[BusinessDomainId])+0",
            "formatString": "0",
            "lineageTag": "8d3cc3df-6ae9-457d-befc-956cc7244cdc"
          },
          {
            "name": "Use",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "DIVIDE(([Data consumption Purpose Pass count]+[Access entitlement Pass count])/2, [Total DataProducts])+0",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "90258d2d-877d-4687-bf47-dc06ea0b7bff"
          },
          {
            "name": "Use heath staus",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            [Use] > [Max_Thresh hold], \"Healthy\", ",
              "                            [Use] > [Min_Thresh hold]&& [Use] <= [Max_Thresh hold], \"Fair\",",
              "                             \"Not healthy\")"
            ],
            "lineageTag": "457163e4-529f-40d5-8a95-ed5577b57980"
          },
          {
            "name": "Use thresh hold",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": [
              "SWITCH(TRUE(),",
              "                            ",
              "                            [Use] >= [Max_Thresh hold], \" #80D091\", ",
              "                            [Use] >= [Min_Thresh hold] && [Use] < [Max_Thresh hold],\"#E8CC78\",",
              "                             \"#F1BBBC\")"
            ],
            "lineageTag": "e7e0f6a9-3468-40be-8dbd-8e07ae198037"
          },
          {
            "name": "Total assets",
            "expression": "SUMX(DataProduct,[AssetCount])+0",
            "formatString": "0",
            "lineageTag": "8ddc5f73-4a8d-468d-bf70-0a1fbd9938e0"
          },
          {
            "name": "ClassificationCheck",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "IF(DataProduct[Classifiaction pass count]>0,100, 0)",
            "lineageTag": "e40ff5d1-f6fa-477a-82ae-cfccb96fb4eb"
          }
        ],
        "partitions": [
          {
            "name": "DataProduct",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataProduct\" = Source{[Schema= DATABASE_SCHEMA,Item=\"DataProduct\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataProduct\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DataProductDataAssetAssociation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6a82698-29c5-4e57-ab24-4276fd4c8e03",
            "sourceColumn": "DataProductId",
            "summarizeBy": "none"
          },
          {
            "name": "DataAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab4f9105-383a-4b7e-a4bb-fbc40e175c00",
            "sourceColumn": "DataAssetId",
            "summarizeBy": "none"
          },
          {
            "name": "Asset link",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "WebUrl",
            "dataType": "string",
            "expression": [
              "\"https://purview.microsoft.com/datacatalog/governance/main/catalog/dataProducts/dataAssetDetail?tid=\" & LOWER(FIRSTNONBLANK(AccountInfo[TenantId], True())) &",
              "\"&dataAssetId=\"&LOWER(DataProductDataAssetAssociation[DataAssetId])&",
              " \"&sourceDataProductId=\"& LOWER(DataProductDataAssetAssociation[DataProductId])"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "65c7227d-d1ac-49fc-8e55-5041cba8751f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "85660211-deff-4cb3-963f-ed539531d13e",
        "partitions": [
          {
            "name": "DataProductDataAssetAssociation",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataProductDataAssetAssociation\" = Source{[Schema= DATABASE_SCHEMA,Item=\"DataProductDataAssetAssociation\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_DataProductDataAssetAssociation\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BusinessDomainDataProductAssociation",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "82aec21e-2fc3-4feb-9de9-cb27d7d60b85",
            "sourceColumn": "DataProductId",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "lineageTag": "31d95a76-065c-41f2-9c8a-a0af3fb3376a",
            "sourceColumn": "BusinessDomainId",
            "summarizeBy": "none"
          },
          {
            "name": "IsPrimaryDataProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "77ce2fd1-dc06-4986-a76c-39943bdb7695",
            "sourceColumn": "IsPrimaryDataProduct",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "5f2992b4-bbe7-4efe-87a5-c806188552cd",
        "partitions": [
          {
            "name": "BusinessDomainDataProductAssociation",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(SERVER, DATABASE),",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomainDataProductAssociation\" = Source{[Schema= DATABASE_SCHEMA,Item=\"BusinessDomainDataProductAssociation\"]}[Data]",
                "in",
                "    #\"ecf09339-34e0-464b-a8fb-661209048543_BusinessDomainDataProductAssociation\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "AccountInfo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "TenantId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41ffd230-ceb2-455f-92da-295278ae41df",
            "sourceColumn": "TenantId",
            "summarizeBy": "none"
          },
          {
            "name": "AccountId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7e71c19-b8a1-4fa6-b7b2-517a60ecabbc",
            "sourceColumn": "AccountId",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "ad76777b-f72a-4a5b-898b-edb5ce69c480",
        "partitions": [
          {
            "name": "AccountInfo",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = #table({\"TenantId\",\"AccountId\"},{{#\"TENANT_ID\", #\"DATABASE_SCHEMA\"}})",
                "in",
                "    Source"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_24e468f1-a0f9-464a-9d0f-f2b940adcac3",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a8d90633-01e4-4f35-868d-cc67987c21ea",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "cbc94d6a-4385-4305-9ef5-32e0af58570f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f4edd321-d64b-41f0-ad27-4bda88a4d655",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3c1ce0bd-95a6-4032-9866-843a17220e73",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "58068c03-d912-4367-8f88-8aae93964439",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "56db14ee-c374-4dcf-a64b-d1e34270a055",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "56cdea80-bd98-4144-82f2-277756895a79",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "baf042ed-6952-4007-94d8-1acb71842629",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4eb617af-b622-49f0-8ad5-1c8e5f146859",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "353c5b2a-15ac-429a-9c97-73b44583031e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0adf8f82-5ba0-4004-a633-4ad642865a80",
                "ordinal": 3
              }
            ],
            "lineageTag": "14efd4fd-85ca-4566-a3b3-e0675085fbac"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "6a86d9f3-e926-4f82-9c8e-3a4ede4672ad",
        "partitions": [
          {
            "name": "DateTableTemplate_24e468f1-a0f9-464a-9d0f-f2b940adcac3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_1a781283-4229-4adc-b73f-44c01b57a237",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3504f8ba-b2e1-4cfb-854e-4ea006fe391a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1e8f73f9-2cea-4b1d-8f93-ebc5b8d20a56",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "112252fc-5f1d-482d-8488-2171722b5dea",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "186731c2-c41e-4677-b0ec-2754f2c07475",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "3bf7b84b-43d8-4c5b-8230-2c72bb7a6b2f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "84ee9015-5e83-4f2b-8e6f-8adde722643b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "ed3c2f23-547a-4500-b310-c7b7d45fea7f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0af36048-5324-4ed5-998e-9e7c67d57add",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "cd103ee4-110d-486c-bf62-ca182e66db47",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "10df301e-f166-42ae-ac9e-c0f75b0a0961",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "639752cd-1de4-4dfe-817c-e25bbf0da58f",
                "ordinal": 3
              }
            ],
            "lineageTag": "d2a77ae7-526e-4d8a-97c3-df8b85f29f1b"
          }
        ],
        "isHidden": true,
        "lineageTag": "fd6c9dbf-a106-4709-8156-cb5988078360",
        "partitions": [
          {
            "name": "LocalDateTable_1a781283-4229-4adc-b73f-44c01b57a237",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('BusinessDomain'[CreatedAt])), 1, 1), Date(Year(MAX('BusinessDomain'[CreatedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_e10937e5-1565-4815-a893-0cb38d197e1d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9a542b2d-8b47-4eb1-99e9-4088b5c30914",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "37c5cc58-4272-4fda-885c-8802e0adc234",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e15afcbd-0cdf-4303-b7e9-9521af4fb78a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d0280246-1e7c-4830-b4f5-954b2e1e03dc",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "ce2f07f7-fecf-49f4-b084-5b75817d6c78",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f3be067d-ce23-46f7-832c-c03b8b7d6f12",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "7fbb7ce7-640e-4e11-ab14-bd12841f07c3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a1023058-0d02-46fc-beaa-0a01f1d421ae",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "746885ce-7fbe-4586-b844-c92db139e0c8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "add7a420-5327-4876-afce-a35aa36233fc",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f1b2972f-d82a-449a-9d82-54300f3819cd",
                "ordinal": 3
              }
            ],
            "lineageTag": "8614bb32-55e3-497c-922b-8b4792a5751f"
          }
        ],
        "isHidden": true,
        "lineageTag": "5c0e54a5-5d6e-4efc-acde-c290bf8f6583",
        "partitions": [
          {
            "name": "LocalDateTable_e10937e5-1565-4815-a893-0cb38d197e1d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('BusinessDomain'[ModifiedAt])), 1, 1), Date(Year(MAX('BusinessDomain'[ModifiedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_bf07079e-7d93-4615-9d40-6645a046cbb1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5610301f-5d16-4a90-b2b8-796435667ee6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c96b8b5f-1b74-4a5d-8739-d871cf3ee7a7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "09fc2cbc-9d5d-490e-9302-bc1774770902",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b324f146-8956-47cb-8800-c0a23086796e",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "117ffd72-04e5-4218-9cb4-1c59dd3061cb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8e82a739-4a06-456f-8bdc-92e1b3f8fa1e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c388b5fb-ba12-4c32-85ed-7cc6800e2f1d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "86bf1e4b-c436-48da-be6e-d309d290f09d",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "bf4e37ec-8f56-4d7f-b1bc-3e6f2e50f780",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "21082ea0-6559-44b3-8e58-ef03be2ed53e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a507ae9b-cd99-4f59-8ae0-6e61dfcc52ed",
                "ordinal": 3
              }
            ],
            "lineageTag": "ca518cd7-424f-4641-8e0b-0e496e76f141"
          }
        ],
        "isHidden": true,
        "lineageTag": "3b9edcc2-f276-4b79-b29e-275c2dbe3bb5",
        "partitions": [
          {
            "name": "LocalDateTable_bf07079e-7d93-4615-9d40-6645a046cbb1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('BusinessDomain'[LastRefreshedAt])), 1, 1), Date(Year(MAX('BusinessDomain'[LastRefreshedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_f131eda2-0aca-4b68-b3d5-c0294d9c91b9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "d3b598c1-2bcb-4bc2-a6d0-19b84bd61374",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "d4c8f2c9-b178-4034-92eb-68901ce9f7ce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e01f6a87-d7b7-4318-a341-6b6aaa63a6a8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6bb1c7a8-610d-4906-a7cb-921e225160ab",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "4dc60dcf-013e-42eb-ab81-de6a87c2f440",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "dec34624-f4bb-455b-a29c-598926a23b32",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9bd3e512-1909-45ee-b6a3-8593c6f55dda",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1dce0e5a-91f1-4d34-a59c-fc0138a6cbf3",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "93c18e22-67ce-4105-9e86-e9705e58c37e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0d904cb3-4e15-4cce-ae22-b95ebd106ce0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2a4b53c3-ccd7-402c-b322-4e7c7ecb4640",
                "ordinal": 3
              }
            ],
            "lineageTag": "d26ebf3a-8b88-415c-995e-40fabca228b9"
          }
        ],
        "isHidden": true,
        "lineageTag": "319d8387-c867-49a4-9f78-1ab69b10b2c9",
        "partitions": [
          {
            "name": "LocalDateTable_f131eda2-0aca-4b68-b3d5-c0294d9c91b9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('BusinessDomainTrends'[LastRefreshedAt])), 1, 1), Date(Year(MAX('BusinessDomainTrends'[LastRefreshedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_f82869d4-3d7a-42c6-ab8a-63d24cacffef",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "88668c80-1852-47a5-83b3-7032d7ee8e7b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f0b348c2-db9e-4c4f-9ee8-d45c2fe6e6e0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "409cab8a-6886-47c6-ba13-d11ce543e369",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "193e2396-28f7-4b4f-ad9c-72a5cd120fbf",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "6c32c7e7-ab8c-4fe4-8497-f643ec8ea709",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "316c299f-fdd8-465d-9129-d838f85e2091",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "619ae264-c66f-4fd0-8f63-7b0f4172730c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0b6ab3fd-1aac-4552-a9d9-b8abba54fdcd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "70b8f448-3873-44ab-9b4d-0c8127ecf504",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e2643fb6-96dc-4258-9c7c-84c88d0ced7b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "cfa743a5-239f-456f-8ffc-f0c3fd75d04d",
                "ordinal": 3
              }
            ],
            "lineageTag": "b4dd7890-96f3-49a0-b298-651140c05103"
          }
        ],
        "isHidden": true,
        "lineageTag": "5b432cb2-41d1-4138-9bfc-a14168ebc8f2",
        "partitions": [
          {
            "name": "LocalDateTable_f82869d4-3d7a-42c6-ab8a-63d24cacffef",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('BusinessDomainTrends'[Date])), 1, 1), Date(Year(MAX('BusinessDomainTrends'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_f2f409b3-7974-42ec-9085-79b92fdb4512",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "b84c4cc7-41f0-43b5-b91e-8e2923ea2a01",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "3ee7aa4c-bf2b-42fd-8d47-3b83ebcf8bae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "de51c39e-59db-4fa2-87d4-3aeff88d426b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "386f9be5-4772-499b-b0b3-2d3a60b9124b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "619d908f-a8fb-4166-9291-2301f811a9f0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "823a8d34-1400-431d-b73a-70ec38747a09",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "bbaf3dad-5395-44bc-a372-d00953d78a37",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1afb3c13-14df-46b7-a439-1e7a9ea347bc",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "49d686d5-42e4-46ef-8785-d4ffef4a54d1",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "63c0b7cc-c83e-4458-89d4-43b48d898930",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "ced3e107-4973-492c-9a1c-ac01b32b3436",
                "ordinal": 3
              }
            ],
            "lineageTag": "63846e72-2c89-4480-aac6-7df0709de48d"
          }
        ],
        "isHidden": true,
        "lineageTag": "b838cd01-7089-4bba-b48c-3eeb889427e6",
        "partitions": [
          {
            "name": "LocalDateTable_f2f409b3-7974-42ec-9085-79b92fdb4512",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DataAsset'[CreatedAt])), 1, 1), Date(Year(MAX('DataAsset'[CreatedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_dc5105f7-f7ce-4920-b48f-69b004eb5475",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ba2f2e19-f9fb-40a1-94e6-e0806bb830be",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "cdca3349-05f2-4721-9445-a07ca73c16ad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c23f5fbd-19ae-4a78-8604-0435d8fc5b37",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ed6d948c-a8ea-44fd-a190-dbd435d81c2f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "87cc9235-ea82-4a29-a4e2-750a02a30ba8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "fa7bfb46-10e5-43c6-8621-6828fdc8d3b6",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "19c9c23f-edbd-4bbc-974a-f135e874ba7a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "255af4cf-029b-4fb0-8181-4b580552f407",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "93f38c8a-22de-40fc-b7e9-70c6cc3d7ac0",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "23df3397-46e5-44ca-8702-37e9194fb821",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "efd8809b-32c1-4cf1-a2ae-ffe7fe833826",
                "ordinal": 3
              }
            ],
            "lineageTag": "24bb9305-ed4a-4954-ac51-43050ed32427"
          }
        ],
        "isHidden": true,
        "lineageTag": "b30e220c-74e2-4d36-b87a-8dab1e10eff7",
        "partitions": [
          {
            "name": "LocalDateTable_dc5105f7-f7ce-4920-b48f-69b004eb5475",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DataAsset'[ModifiedAt])), 1, 1), Date(Year(MAX('DataAsset'[ModifiedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_73e8efaf-35c9-4c93-b507-e5feca1c6f31",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dbfb81c1-6838-462b-a239-b2f7a4c90504",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0fc9a8b9-dd6d-41ea-a72c-1b4f780b7cd7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "bd333640-5037-432b-84f5-a3674b7efbd5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4e991541-45ef-47e3-8ede-5d69e9f462a8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "e1119abb-5a83-480b-a8cd-6e9e90a30adf",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "22c05169-da47-4d17-a642-672dd171be5b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "ef3b1d53-fc3b-4569-82a0-e3d4e5396377",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "1bbb8423-ae36-47a2-a6c4-24ebea67484a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4a21144f-e15d-489d-9315-81cf84e7e279",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3bb2104c-c898-4b79-9ddb-751f8e492d0a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e1ac20d4-6f0f-4c1b-9e24-172df75a7c86",
                "ordinal": 3
              }
            ],
            "lineageTag": "9542f612-5032-42e3-bf68-1799a508ddec"
          }
        ],
        "isHidden": true,
        "lineageTag": "b02595b0-830b-438c-bbe3-cb8b934e64f2",
        "partitions": [
          {
            "name": "LocalDateTable_73e8efaf-35c9-4c93-b507-e5feca1c6f31",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DataAsset'[LastRefreshedAt])), 1, 1), Date(Year(MAX('DataAsset'[LastRefreshedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c5729d02-5865-4ccf-982c-f06355c7ef59",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "13ea108b-6c37-4e6e-b13e-811398b4a257",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f8612ad4-abbb-405d-a31e-a10e9eadc7b4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "551a8973-4266-4a4a-86e9-fcdf649cb319",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "41c146cf-8269-45aa-8d71-c87c6cdc2419",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d3fe3abf-3022-4530-a075-72496d9f2c8a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "bebf4a60-42f1-4663-a434-9910cabea832",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3af778bc-8227-4caa-9152-d01ea31d4b9c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f3569978-4207-4339-89d8-a5ef15a5264c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fdeb23c5-76f4-48a0-ae05-400bf11636d0",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1f450833-9795-4f72-b1a7-edbb286821bb",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3f2244df-9a18-4591-9ccb-c55441725a13",
                "ordinal": 3
              }
            ],
            "lineageTag": "a89486c6-695c-4c84-ba42-ea7c90ed030b"
          }
        ],
        "isHidden": true,
        "lineageTag": "6d4eba8a-0178-4975-aa1f-3f9ebbd5c1ac",
        "partitions": [
          {
            "name": "LocalDateTable_c5729d02-5865-4ccf-982c-f06355c7ef59",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DataProduct'[CreatedAt])), 1, 1), Date(Year(MAX('DataProduct'[CreatedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d051808b-15ef-4bf6-9e9d-f5058ce87f03",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c60ff48f-b12f-4af5-a6e3-dc0b4abe39ef",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ba27b93f-2a80-4b37-ac55-e83844441f24",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0dad86ca-d634-4cbf-954f-a20cf64f55bb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f2e04887-d37f-4ad9-a102-7a339b2a9747",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8f2ae185-7d17-44fa-a9be-cfbb56b6815b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "61cc4d46-1118-4c3a-82c7-59bc094b4a59",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "52dffbf7-67db-47b5-9c74-065951ccd799",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "c9eac5f1-ef15-4b9c-b674-7124556ccf73",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "473e8f3b-a360-4d57-9640-57ee67fb6089",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "22363837-f048-4f70-9d94-0ba07c146e4c",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "f4ed0bb8-5029-443c-9e15-1b7705d5e681",
                "ordinal": 3
              }
            ],
            "lineageTag": "68d430fa-6e2e-4da5-8d04-52111d34dddc"
          }
        ],
        "isHidden": true,
        "lineageTag": "c0d5befe-d69f-4b3b-9146-347c27e5770f",
        "partitions": [
          {
            "name": "LocalDateTable_d051808b-15ef-4bf6-9e9d-f5058ce87f03",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DataProduct'[ModifiedAt])), 1, 1), Date(Year(MAX('DataProduct'[ModifiedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_bdccc7ef-9651-46a6-b933-f2709936cb95",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "379a5297-b320-4f92-9c72-ea32427d495b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "6f1d16bd-2e3d-487a-9409-e5134d6b52aa",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "f7edac79-bc5d-45f6-a6b5-f4a1cec4b004",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "30811a76-64ab-4bb8-bd8e-c013a50dec83",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d82ff840-b08b-40d1-b679-138671bf821d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0943578b-b4a1-453d-a5ac-fbbef581f679",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "1e0b6fa1-71ed-443d-a9c2-5bb2b9729fd0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b23ca397-4d78-4966-a00c-1e942f4ae1b6",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "fa379197-7142-45bd-97ad-79a9cc6faf01",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e1566f63-74a5-4b02-b42d-082702d81ab2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "8fb4fd5c-f630-49be-88ab-05048a25e26e",
                "ordinal": 3
              }
            ],
            "lineageTag": "0c790dfb-fe9f-487b-98a9-0f3c639e4fa1"
          }
        ],
        "isHidden": true,
        "lineageTag": "13dd5515-563f-4dd3-b9ab-800ece5c50f4",
        "partitions": [
          {
            "name": "LocalDateTable_bdccc7ef-9651-46a6-b933-f2709936cb95",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('DataProduct'[LastRefreshedAt])), 1, 1), Date(Year(MAX('DataProduct'[LastRefreshedAt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}