class AtlasRddCommonVariables:
    DefaultClassificationCategory="Micosoft"
    CustomClassificationCategory = "Custom"
    SensitiveClassificationCategory = "Sensitive"
    LabelClassificationCategory = "Label"
    regex_adf = ".*\/Microsoft.DataFactory\/factories\/"
    regex_adf_replacement = "adf:\/\/"
    regex_adls = "\..*[^(blob)]\.core\.windows"
    regex_adls_replacement = "\.core\.windows"
    regex_hive_fqn = ".*\@"
    regex_hive_fqn_replacement = "z"
    regex_power_bi = "(app\.powerbi\.com\/groups\/)"
    regex_postgres_sql = ".*:\/\/servers\/"
    regex_postgres_sql_replacement = "postgresql:\/\/"
    regex_synapse_fqn = "\..*\.azuresynapse"
    regex_synapse_ondemand_fqn = "(\-ondemand\.azuresynapse)"
    regex_synapse_ondemand_fqn_replacement = ".azuresynapse"
    regex_synapse_fqn_replacement = "\.azuresynapse"
