//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Purview.DataEstateHealth.BusinessLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Purview.DataEstateHealth.BusinessLogic.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create assessment on Control type &quot;{0}&quot;.
        /// </summary>
        internal static string ErrorMessageAddAssessmentOnlyOnNode {
            get {
                return ResourceManager.GetString("ErrorMessageAddAssessmentOnlyOnNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update or delete system defined entity..
        /// </summary>
        internal static string ErrorMessageCannotChangeSystemDefinedEntity {
            get {
                return ResourceManager.GetString("ErrorMessageCannotChangeSystemDefinedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete {0} with id &quot;{1}&quot; as it is referenced in {2} with ids {3}..
        /// </summary>
        internal static string ErrorMessageDeleteFailureEntityReferenced {
            get {
                return ResourceManager.GetString("ErrorMessageDeleteFailureEntityReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with id &quot;{1}&quot; already exists..
        /// </summary>
        internal static string ErrorMessageEntityAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorMessageEntityAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with id &quot;{1}&quot; does not exist..
        /// </summary>
        internal static string ErrorMessageEntityDoesNotExist {
            get {
                return ResourceManager.GetString("ErrorMessageEntityDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with {1} &quot;{2}&quot; already exists..
        /// </summary>
        internal static string ErrorMessageEntityFieldAlreadyExists {
            get {
                return ResourceManager.GetString("ErrorMessageEntityFieldAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have permission to change {0} in business domain {1}..
        /// </summary>
        internal static string ErrorMessageForbiddenMessage
        {
            get
            {
                return ResourceManager.GetString("ErrorMessageForbiddenMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot delete {0} with id &quot;{1}&quot; as it is referenced in {2} with ids {3}..
        /// </summary>
        internal static string ErrorMessageEntityReferenced {
            get {
                return ResourceManager.GetString("ErrorMessageEntityReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have permission to read {0} in business domain {1}..
        /// </summary>
        internal static string ErrorMessageForbiddenReadMessage {
            get {
                return ResourceManager.GetString("ErrorMessageForbiddenReadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create or update controls with InDevelopment status..
        /// </summary>
        internal static string ErrorMessageInDevelopStatus {
            get {
                return ResourceManager.GetString("ErrorMessageInDevelopStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity type {0} is not supported..
        /// </summary>
        internal static string ErrorMessageInvalidEntityType {
            get {
                return ResourceManager.GetString("ErrorMessageInvalidEntityType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find statusPaletteConfig on control and all parent control groups..
        /// </summary>
        internal static string ErrorMessageMissingStatusPaletteConfig {
            get {
                return ResourceManager.GetString("ErrorMessageMissingStatusPaletteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; cannot be changed. Old value: &quot;{1}&quot;. New value: &quot;{2}&quot;..
        /// </summary>
        internal static string ErrorMessagePropertyCannotBeChanged {
            get {
                return ResourceManager.GetString("ErrorMessagePropertyCannotBeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &quot;{0}&quot; is required..
        /// </summary>
        internal static string ErrorMessagePropertyRequired {
            get {
                return ResourceManager.GetString("ErrorMessagePropertyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the referenced {0} with id(s) {1}..
        /// </summary>
        internal static string ErrorMessageReferenceNotFound {
            get {
                return ResourceManager.GetString("ErrorMessageReferenceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referenced {0} in property &quot;{1}&quot; with id {2} has a wrong type &quot;{3}&quot;. Valid types are {4}..
        /// </summary>
        internal static string ErrorMessageReferenceNotMatch {
            get {
                return ResourceManager.GetString("ErrorMessageReferenceNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} id in the payload &quot;{1}&quot; doesn&apos;t match the URL parameter &quot;{2}&quot;..
        /// </summary>
        internal static string ErrorMessageUpdateEntityIdNotMatch {
            get {
                return ResourceManager.GetString("ErrorMessageUpdateEntityIdNotMatch", resourceCulture);
            }
        }
    }
}
