parameters:
- name: deployType
  type: string
  displayName: Deploy Type
  default: minor
  values:
  - major
  - minor
  - powerBi

- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

trigger: none

extends:
  template: templates/DataEstateHealth.EnvironmentsBase.yml
  parameters:
    pdgEnvironment: dev
    deployType: ${{ parameters.deployType }}
    debug: ${{ parameters.debug }}