trigger:  
 batch: true
 branches:
  exclude:
    - main

parameters:
- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

resources:
  repositories: 
  - repository: pdgTemplates
    type: git
    name: SharedYamlTemplates
    ref: refs/heads/main

extends:
  template: v1/Pdg.Build.Containers.Buddy.yml@pdgTemplates
  parameters:
    containersToPackage:
    - ApiService
    - WorkerService
    buildSolution: dirs.proj
    majorVersion: 1
    minorVersion: 0
    debug: ${{ parameters.debug }}
    postBuildSteps:
    - template: DataEstateHealth.Build.PostBuildSteps.yml