parameters:
- name: deployType
  type: string
  displayName: Deploy Type
  default: minor
  values:
  - major
  - minor
  - powerBi
  - dataDomain


- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

trigger:  
 batch: true
 branches:
  include:
  - main

resources:
  repositories: 
  - repository: pdgTemplates
    type: git
    name: SharedYamlTemplates
    ref: refs/heads/main

extends:
  template: v1/Pdg.Release.Containers.NonOfficial.yml@pdgTemplates
  parameters:
    containersToPackage:
    - ApiService
    - WorkerService
    buildSolution: dirs.proj
    majorVersion: 1
    minorVersion: 0
    customTestArgs: -e AZURE_TENANT_ID=72f988bf-86f1-41af-91ab-2d7cd011db47 -e AZURE_CLIENT_ID=5a352a7c-80b5-4e91-b89e-7c2c86f37bd6 -e AZURE_CLIENT_CERTIFICATE_PATH=$(Build.SourcesDirectory)/e2eclient-certificate.pfx -e AZURE_CLIENT_SEND_CERTIFICATE_CHAIN=true
    debug: ${{ parameters.debug }}
    regions: '*'
    rolloutSpecPath: Ev2Deployment/Ev2ServiceArtifactsRoot/rolloutSpec.${{parameters.deployType}}.json
    serviceRootPath: Ev2Deployment/Ev2ServiceArtifactsRoot
    alias: "DataEstateHealth"
    preBuildSteps:
    - template: templates/DataEstateHealth.DownloadE2EClientCertificate.yml
    postBuildSteps:
    - template: templates/DataEstateHealth.PostBuildSteps.yml
    otherReleaseStages: 
    - ${{ if eq(parameters['deployType'],'powerBi')}}:
      - template: v1/stages/Pdg.Release.Base.yml@pdgTemplates
        parameters:
          ob_release_environment: Test
          regions: '*'
          rolloutSpecPath: drop_build_buildContainersLinux/Ev2Deployment/Ev2ServiceArtifactsRoot/rolloutSpec.powerBI.major.json
          serviceRootPath: drop_build_buildContainersLinux/Ev2Deployment/Ev2ServiceArtifactsRoot
          pdgEnvironment: Dogfood
          alias: 'DataEstateHealthPowerBI'
    - ${{ if eq(parameters['deployType'],'dataDomain')}}:
      - template: v1/stages/Pdg.Release.Base.yml@pdgTemplates
        parameters:
          ob_release_environment: Test
          regions: '*'
          rolloutSpecPath: drop_build_buildContainersLinux/Ev2Deployment/Ev2ServiceArtifactsRoot/rolloutSpec.dataDomain.major.json
          serviceRootPath: drop_build_buildContainersLinux/Ev2Deployment/Ev2ServiceArtifactsRoot
          pdgEnvironment: Dogfood
          alias: 'DataEstateHealthDataDomain'