parameters:
- name: deployType
  type: string
  displayName: Deploy Type
  default: minor
  values:
  - major
  - minor
  - powerBi

- name: 'debug'
  displayName: 'Enable debug output'
  type: boolean
  default: false

trigger:  
 batch: true
 branches:
  include:
  - main

resources:
  repositories: 
  - repository: pdgTemplates
    type: git
    name: SharedYamlTemplates
    ref: refs/heads/main

extends:
  template: v1/Pdg.Release.Containers.NonOfficial.yml@pdgTemplates
  parameters:
    containersToPackage:
    - ApiService
    - WorkerService
    buildSolution: dirs.proj
    majorVersion: 1
    minorVersion: 0
    debug: ${{ parameters.debug }}
    regions: '*'
    rolloutSpecPath: Ev2Deployment/Ev2ServiceArtifactsRoot/rolloutSpec.${{parameters.deployType}}.json
    serviceRootPath: Ev2Deployment/Ev2ServiceArtifactsRoot
    alias: "DataEstateHealth"
    postBuildSteps:
    - template: DataEstateHealth.Build.PostBuildSteps.yml
    otherReleaseStages: 
    - ${{ if eq(parameters['deployType'],'powerBi')}}:
      - template: v1/stages/Pdg.Release.Base.yml@pdgTemplates
        parameters:
          ob_release_environment: Test
          regions: '*'
          rolloutSpecPath: drop_build_buildContainersLinux/Ev2Deployment/Ev2ServiceArtifactsRoot/rolloutSpec.powerBI.major.json
          serviceRootPath: drop_build_buildContainersLinux/Ev2Deployment/Ev2ServiceArtifactsRoot
          pdgEnvironment: Dogfood
          alias: 'DataEstateHealthPowerBI'