{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SERVER\",\"DATABASE\",\"DATABASE_SCHEMA\",\"TENANT_ID\",\"DirectQuery to AS - Data_Governance_Dataset\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.123.742.0 (23.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "SERVER",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"dghdogfoodsynapse-ondemand.sql.azuresynapse.net\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "a14b6f22-ea8d-4a8e-97f2-05710f062eb1"
      },
      {
        "name": "DATABASE",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"health_1\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "953805ba-bf53-4776-ad5b-7ae663b34473"
      },
      {
        "name": "TENANT_ID",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"79e7043b-2d89-4454-9f07-1d8ceb3f0399\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "17e0cb58-b472-4281-a56f-7015df8fa2d7"
      },
      {
        "name": "DirectQuery to AS - Data_Governance_Dataset",
        "annotations": [
          {
            "name": "PBI_IncludeFutureArtifacts",
            "value": "True"
          },
          {
            "name": "PBI_RemovedChildren",
            "value": "[{\"remoteItemId\":{\"analysisServicesObject\":{\"sourceName\":null,\"sourceLineageTag\":\"4ba41ebe-be7a-456f-804b-e15425e3986e\"}},\"objectType\":\"Table\"}]"
          }
        ],
        "expression": [
          "let",
          "    Source = AnalysisServices.Database(\"powerbi://df-msit-scus-redirect.analysis.windows.net/v1.0/myorg/InsightsWorkspace\", \"Data_Governance_Dataset\"),",
          "    Cubes = Table.Combine(Source[Data]),",
          "    Cube = Cubes{[Id=\"Model\", Kind=\"Cube\"]}[Data]",
          "in",
          "    Cube"
        ],
        "kind": "m",
        "lineageTag": "e2ba397e-6e64-4c01-ab64-ca44aec345a7"
      }
    ],
    "relationships": [
      {
        "name": "d80eaafc-2c22-434f-a551-3266342c04a4",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "BusinessDomainId",
        "fromTable": "BusinessDomainTrends",
        "toColumn": "BusinessDomainId",
        "toTable": "BusinessDomain"
      },
      {
        "name": "d73a5b36-aaf1-4e42-a877-1e1dfaf658c9",
        "fromColumn": "DataAssetId",
        "fromTable": "DataAssetContactAssociation",
        "toColumn": "DataAssetId",
        "toTable": "DataAsset"
      },
      {
        "name": "2b8e878f-4ba5-4641-9099-290d30a04252",
        "fromColumn": "DataProductId",
        "fromTable": "DataProductContactAssociation",
        "toColumn": "DataProductId",
        "toTable": "BusinessDomainDataProductAssociation"
      },
      {
        "name": "ca429e9a-0df5-4614-9edd-4d63958f1104",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DataAssetId",
        "fromTable": "DataProductDataAssetAssociation",
        "toColumn": "DataAssetId",
        "toTable": "DataAsset"
      },
      {
        "name": "3c6923bf-ea1b-4e37-b62a-686a7654e8be",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DataProductId",
        "fromTable": "DataProductDataAssetAssociation",
        "toCardinality": "many",
        "toColumn": "DataProductId",
        "toTable": "BusinessDomainDataProductAssociation"
      },
      {
        "name": "e601abcb-912f-4618-949b-4c44a4e36c2a",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "BusinessDomainId",
        "fromTable": "BusinessDomainDataProductAssociation",
        "toColumn": "BusinessDomainId",
        "toTable": "BusinessDomain"
      },
      {
        "name": "f2abd0f9-aac5-4964-bdee-f0e05fc36516",
        "crossFilteringBehavior": "bothDirections",
        "fromColumn": "DataProductId",
        "fromTable": "BusinessDomainDataProductAssociation",
        "toColumn": "DataProductId",
        "toTable": "DataProduct"
      },
      {
        "name": "a3d04a5d-5ddf-420f-be35-76b8aff0271d",
        "fromColumn": "DataProductId",
        "fromTable": "AssetURLTable",
        "toColumn": "DataProductId",
        "toTable": "BusinessDomainDataProductAssociation"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DATABASE_SCHEMA",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "columns": [
          {
            "name": "DATABASE_SCHEMA",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82cf0ed9-dfd4-4add-90f0-b26f13e453bd",
            "sourceColumn": "DATABASE_SCHEMA",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4ba41ebe-be7a-456f-804b-e15425e3986e",
        "partitions": [
          {
            "name": "DATABASE_SCHEMA",
            "mode": "import",
            "source": {
              "expression": "\"ecf09339-34e0-464b-a8fb-661209048543\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "BusinessDomain",
        "columns": [
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "568f531a-dc39-4fe9-9730-83c758ab22e8",
            "sourceColumn": "BusinessDomainId",
            "sourceLineageTag": "212cb632-0b48-471f-a1aa-3a469eb3c09e",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainDisplayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "9baf9977-42f0-4479-9aee-2fadc7eeaefc",
            "sourceColumn": "BusinessDomainDisplayName",
            "sourceLineageTag": "75f3b3b2-2ba0-40a1-a99e-53c5bd3c871c",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "1005353d-3774-43d2-b5aa-bfaca0aabea2",
            "sourceColumn": "CreatedAt",
            "sourceLineageTag": "08c01862-e173-4e62-b69a-ed5c8879aad9",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "e3adf8e9-57c5-409e-af1a-4295213160ba",
            "sourceColumn": "CreatedBy",
            "sourceLineageTag": "3beb56d3-32d6-43f0-aa47-92e94d8c9057",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "014ac703-c0a3-487e-9798-928234a58f04",
            "sourceColumn": "ModifiedAt",
            "sourceLineageTag": "a4bb3cea-6aa4-44e6-96d8-2c99ee9a77f0",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "f9dfc033-39cd-4ef0-9c9b-3a3209d9b1b9",
            "sourceColumn": "ModifiedBy",
            "sourceLineageTag": "2121ab79-072d-4384-8f6c-91425126e0e7",
            "summarizeBy": "none"
          },
          {
            "name": "GlossaryTermCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "14dd035c-e50d-4295-8078-1c197458878b",
            "sourceColumn": "GlossaryTermCount",
            "sourceLineageTag": "3907d87a-7141-407c-977b-6949beb885e8",
            "summarizeBy": "sum"
          },
          {
            "name": "DataProductCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dd885463-bfd9-460c-b376-7bc81f2f3dc1",
            "sourceColumn": "DataProductCount",
            "sourceLineageTag": "425f02e6-9961-4222-982c-280454a68013",
            "summarizeBy": "sum"
          },
          {
            "name": "IsRootDomain",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "b7502ad4-6a7f-449e-a52c-8080c9c1b936",
            "sourceColumn": "IsRootDomain",
            "sourceLineageTag": "8e39a308-b872-4700-8e7d-ce9bfa97f261",
            "summarizeBy": "none"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "1094aeec-edca-41be-ba61-a1c56f1465a0",
            "sourceColumn": "LastRefreshedAt",
            "sourceLineageTag": "1540c7e8-9007-48e8-a2e2-f9948f52e22f",
            "summarizeBy": "none"
          },
          {
            "name": "HasValidOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "6baed882-9dc4-403c-b5b5-6b6e3731037c",
            "sourceColumn": "HasValidOwner",
            "sourceLineageTag": "d623da40-2e4e-43dc-af07-50e0e3e293b7",
            "summarizeBy": "none"
          },
          {
            "name": "HasDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "4e06a67c-f425-4c89-819b-14c62a02c37f",
            "sourceColumn": "HasDescription",
            "sourceLineageTag": "98e0d34a-2072-4c16-9174-d3ce094482d1",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0b70c96a-b350-4204-a956-085d2fe4df75",
        "partitions": [
          {
            "name": "BusinessDomain",
            "mode": "directQuery",
            "source": {
              "entityName": "BusinessDomain",
              "expressionSource": "DirectQuery to AS - Data_Governance_Dataset",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "bb22e2b4-7b67-4278-bc82-0426adf76ee0"
      },
      {
        "name": "BusinessDomainTrends",
        "columns": [
          {
            "name": "BusinessDomainTrendId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "b75786d8-a6d8-477b-a7c2-40993c453358",
            "sourceColumn": "BusinessDomainTrendId",
            "sourceLineageTag": "06c090aa-0a25-4ca5-99a5-717053f799a8",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "e5d479a4-92c4-462a-9270-103d60114d33",
            "sourceColumn": "BusinessDomainId",
            "sourceLineageTag": "33b8338e-8f90-4470-934a-8586ee981f19",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f1747c9e-880f-439f-bacd-904332307022",
            "sourceColumn": "DataProductCount",
            "sourceLineageTag": "b1b99c18-c54f-46d4-958a-5b57c1721e72",
            "summarizeBy": "sum"
          },
          {
            "name": "AssetCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f8cffc64-c257-4cf4-87d4-0b678a9c5831",
            "sourceColumn": "AssetCount",
            "sourceLineageTag": "48b4dd73-0802-4cec-b32b-4e5ab3d6ef2e",
            "summarizeBy": "sum"
          },
          {
            "name": "ClassificationPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "22a68e5d-7b6f-44a0-b9ea-5fd30ed9a998",
            "sourceColumn": "ClassificationPassCount",
            "sourceLineageTag": "3e913fd3-503b-49f8-a31b-21cb5004f942",
            "summarizeBy": "sum"
          },
          {
            "name": "GlossaryTermPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8e186ff-db67-41ef-bdd7-dab305ea3058",
            "sourceColumn": "GlossaryTermPassCount",
            "sourceLineageTag": "a55ec180-4a5b-47ce-a84b-685395c2506c",
            "summarizeBy": "sum"
          },
          {
            "name": "DataQualityScorePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7cf52232-add4-48ce-89b8-cf1a1e65f2a6",
            "sourceColumn": "DataQualityScorePassCount",
            "sourceLineageTag": "e9d8d89d-e181-4113-b068-30818381efee",
            "summarizeBy": "sum"
          },
          {
            "name": "ValidDataProductOwnerPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "53da1b06-4fb3-4166-b92b-aa179bb9a258",
            "sourceColumn": "ValidDataProductOwnerPassCount",
            "sourceLineageTag": "1fd02d44-f020-4ff8-a0f6-9504390d2e80",
            "summarizeBy": "sum"
          },
          {
            "name": "DataShareAgreementSetOrExemptPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "af0bbb82-9fad-49a6-ac45-39565e4e81ad",
            "sourceColumn": "DataShareAgreementSetOrExemptPassCount",
            "sourceLineageTag": "d8f00ed5-d02b-43b6-805f-376b7395c218",
            "summarizeBy": "sum"
          },
          {
            "name": "ValidUseCasePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "024a1eca-b234-4e90-ad61-055c1a67115f",
            "sourceColumn": "ValidUseCasePassCount",
            "sourceLineageTag": "728b37aa-9a06-426f-89c6-26541f15ee1b",
            "summarizeBy": "sum"
          },
          {
            "name": "ValidTermsOfUsePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a027d706-fef4-4e80-a813-dc907f2bb024",
            "sourceColumn": "ValidTermsOfUsePassCount",
            "sourceLineageTag": "55f542c4-287f-49ed-bb62-fc70817b339c",
            "summarizeBy": "sum"
          },
          {
            "name": "AccessEntitlementPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5d1c2ae8-0569-4d5c-89c4-bf7723e09f9a",
            "sourceColumn": "AccessEntitlementPassCount",
            "sourceLineageTag": "9fb4438e-0e01-4aad-8185-c9edb551f680",
            "summarizeBy": "sum"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "mmmm d\\, yyyy",
            "lineageTag": "26b81633-2eb7-490b-9a87-d362934eed82",
            "sourceColumn": "LastRefreshedAt",
            "sourceLineageTag": "50bf2db3-bef9-454d-9c9d-7557b81b5469",
            "summarizeBy": "none"
          },
          {
            "name": "TotalOpenActionsCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c557bd0d-8f9b-4568-8692-2978afe8981f",
            "sourceColumn": "TotalOpenActionsCount",
            "sourceLineageTag": "e3e8afa3-9a47-4d1e-b09d-80363a87d37d",
            "summarizeBy": "sum"
          },
          {
            "name": "DataProductDescriptionPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b78f55d7-f187-4f20-a0c3-c172e03fb8f2",
            "sourceColumn": "DataProductDescriptionPassCount",
            "sourceLineageTag": "e3897a97-3cad-4ad7-b375-f5bd0d9ead19",
            "summarizeBy": "sum"
          },
          {
            "name": "AuthoritativeSourcePassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7fae9238-1fdd-4bc3-b1d6-74dd82d57ad4",
            "sourceColumn": "AuthoritativeSourcePassCount",
            "sourceLineageTag": "6f5c36bc-d55b-48ad-9959-614d21bd9899",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "mmmm d\\, yyyy",
            "lineageTag": "9bf763e9-65dc-4461-8ed5-1cd1435afaa1",
            "sourceColumn": "Date",
            "sourceLineageTag": "a4586e51-3a33-42fb-beaa-5e2fafbd4552",
            "summarizeBy": "none"
          },
          {
            "name": "Time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "Long Time",
            "lineageTag": "123e5e16-d3e2-4aef-8799-e7fcbb23d09f",
            "sourceColumn": "Time",
            "sourceLineageTag": "91ac7ecd-d41a-4a53-8173-65b4983ce7b8",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f5f2735c-59ce-4d66-ab64-b44288c442e5",
        "measures": [
          {
            "name": "Trend_Metadata completeness",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Trend_Metadata completeness\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "930857ea-9f7d-4f52-96c3-1573173c7315",
            "sourceLineageTag": "c0b8c886-486a-4d4c-bdf6-7f7d6d88ce16"
          },
          {
            "name": "Trend_Metadata completeness pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Trend_Metadata completeness pass count\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "1a95faed-9dd6-4ec7-b098-cfa75b00bf4c",
            "sourceLineageTag": "2b5906bd-a5fa-477e-a8f6-f66845f465d6"
          },
          {
            "name": "Trend_Quality pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Trend_Quality pass count\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "234ba344-f4b2-4cd5-97b4-b97ba3e1636b",
            "sourceLineageTag": "0f014697-4f30-475a-898a-63e0938a2523"
          },
          {
            "name": "Trend_Use pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Trend_Use pass count\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "daec8b08-b518-454f-ada5-e5a9c8837577",
            "sourceLineageTag": "e0e00cf1-4194-410e-a800-7e49ec4530e1"
          },
          {
            "name": "Trend_Sum of all metrics",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Trend_Sum of all metrics\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "153f2336-d1dc-48bf-8cd7-407807a6ef32",
            "sourceLineageTag": "f7e9d30f-be49-464c-bf16-670acb4219e8"
          },
          {
            "name": "Trend_Overall health score",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Trend_Overall health score\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "35f3d8d9-84bf-410f-992c-fbdfb1463c11",
            "sourceLineageTag": "fa4abfc3-413d-4229-b8df-134e07c870c7"
          },
          {
            "name": "Trend_Quality",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Trend_Quality\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a59e0d64-d6b3-4fd2-b847-775a4e810870",
            "sourceLineageTag": "bba3ffdc-bccc-4086-9755-0fe4eca2ec02"
          },
          {
            "name": "Trend_Use",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Trend_Use\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "53e17ff3-208f-4664-8142-0551182002d8",
            "sourceLineageTag": "5c59a53d-e2d1-42ed-a0c5-8e3953391799"
          },
          {
            "name": "Trend_Asset Pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Trend_Asset Pass count\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "8c871eb8-5609-4446-a523-cd0f7887ee5d",
            "sourceLineageTag": "f539233d-7090-4b2c-bd5a-b10780f26066"
          },
          {
            "name": "Sum of Asset pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Sum of Asset pass count\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "6d9c3566-c844-4dff-b153-7c8ace9a26a1",
            "sourceLineageTag": "533391d1-545e-45af-9d0c-996f3251658f"
          }
        ],
        "partitions": [
          {
            "name": "BusinessDomainTrends",
            "mode": "directQuery",
            "source": {
              "entityName": "BusinessDomainTrends",
              "expressionSource": "DirectQuery to AS - Data_Governance_Dataset",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "d6ae76ed-5409-4399-b782-f93c0a38a783"
      },
      {
        "name": "DataAsset",
        "columns": [
          {
            "name": "DataAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "c54a293a-6907-4dcf-8012-343384b0ac19",
            "sourceColumn": "DataAssetId",
            "sourceLineageTag": "e39026af-ff1f-434e-9062-5b5c98fb7a68",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "f0ed5dac-3823-4b26-bdd6-4a6271db2c1e",
            "sourceColumn": "CreatedAt",
            "sourceLineageTag": "f1e9149d-ec74-4fce-a79e-70964e721c76",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "36800c18-549f-40e1-bebc-cf69c805370f",
            "sourceColumn": "CreatedBy",
            "sourceLineageTag": "91eb7a17-9539-4015-8baa-91f543df2229",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "5f97c1c3-0167-4fa2-ade4-4f9c94fbb96e",
            "sourceColumn": "ModifiedBy",
            "sourceLineageTag": "0f7de614-5aa1-40e8-be9b-eb3e96afaab5",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "cf9ae7ad-49d6-4817-92d4-9cebc2e919df",
            "sourceColumn": "ModifiedAt",
            "sourceLineageTag": "40711738-1686-471a-acda-9ca6c8d7b098",
            "summarizeBy": "none"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "7bbe821e-1dd7-4392-9c14-94ff8dc3b59a",
            "sourceColumn": "LastRefreshedAt",
            "sourceLineageTag": "d96ae37b-f12a-43e7-84af-41f6f2908812",
            "summarizeBy": "none"
          },
          {
            "name": "SourceType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "fe84ea96-fe6f-48a4-a2ae-e2eae1620a53",
            "sourceColumn": "SourceType",
            "sourceLineageTag": "742cc15a-4dc4-4d9e-9b76-c5603dddb9ac",
            "summarizeBy": "none"
          },
          {
            "name": "ObjectType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "985c84fa-bdaa-48cb-8bdc-24c2752be0b9",
            "sourceColumn": "ObjectType",
            "sourceLineageTag": "e0fad8f6-34aa-4c3d-a885-3a133b725801",
            "summarizeBy": "none"
          },
          {
            "name": "HasSchema",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3dfb2179-399a-4e95-90a8-e43e210c50f7",
            "sourceColumn": "HasSchema",
            "sourceLineageTag": "5f1f365b-63fe-4264-8e64-8f2e8b0ca6d8",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "0eb7fdf6-2975-4bf4-8c57-53e903f78862",
            "sourceColumn": "BusinessDomainId",
            "sourceLineageTag": "b33a5eff-5c11-4283-a558-03b47eaa9275",
            "summarizeBy": "none"
          },
          {
            "name": "SourceAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "d8eb73d6-7053-4f22-92c7-8e1c13d7a0df",
            "sourceColumn": "SourceAssetId",
            "sourceLineageTag": "917b9909-257f-4aba-b87e-af54d4c6d5d3",
            "summarizeBy": "none"
          },
          {
            "name": "DisplayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "9d5bb51f-feb9-4ee1-9154-ec9f7e2bca10",
            "sourceColumn": "DisplayName",
            "sourceLineageTag": "4ae23736-3006-4d6c-afa3-1d6061bed88b",
            "summarizeBy": "none"
          },
          {
            "name": "HasClassification",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "783ccec7-a171-4bd3-94ea-67d62037a96a",
            "sourceColumn": "HasClassification",
            "sourceLineageTag": "c73d33cd-137a-4338-87f0-0390894a06de",
            "summarizeBy": "none"
          },
          {
            "name": "HasDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "cd3ed97a-77f8-4154-a9dd-7307d90308cf",
            "sourceColumn": "HasDescription",
            "sourceLineageTag": "cec1fb47-ccff-4e66-8e4c-735d5bae6563",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "6bb717ae-399d-4e66-9a2c-bced42b25153",
        "partitions": [
          {
            "name": "DataAsset",
            "mode": "directQuery",
            "source": {
              "entityName": "DataAsset",
              "expressionSource": "DirectQuery to AS - Data_Governance_Dataset",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "e01a6210-45a2-498b-a38a-192cae8264e8"
      },
      {
        "name": "DataAssetContactAssociation",
        "columns": [
          {
            "name": "DataAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "256a6de9-8d3d-4dac-ac36-7f1c4c2b8d1b",
            "sourceColumn": "DataAssetId",
            "sourceLineageTag": "b9eb9f08-4787-4e2e-bf47-756c7072bb2f",
            "summarizeBy": "none"
          },
          {
            "name": "ContactRole",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "4c85194d-8ce8-4102-b20d-b16b558eb31a",
            "sourceColumn": "ContactRole",
            "sourceLineageTag": "fbab66b3-3042-44cc-b653-2c714744fc1e",
            "summarizeBy": "none"
          },
          {
            "name": "ContactId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "8b7b5a0b-cd7c-40b3-8e0e-e6ef1280e58e",
            "sourceColumn": "ContactId",
            "sourceLineageTag": "8ff104b9-23a3-4036-8b99-8e5135f8cec5",
            "summarizeBy": "none"
          },
          {
            "name": "IsActive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "332e2dab-87a3-44e2-a0af-b5ef8486d425",
            "sourceColumn": "IsActive",
            "sourceLineageTag": "f5837da1-df40-4a24-901c-d8f58ec95f88",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bcb50d26-1101-4362-9abe-e6394b230bd4",
        "partitions": [
          {
            "name": "DataAssetContactAssociation",
            "mode": "directQuery",
            "source": {
              "entityName": "DataAssetContactAssociation",
              "expressionSource": "DirectQuery to AS - Data_Governance_Dataset",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "f6784168-2d61-407e-a710-15511338caef"
      },
      {
        "name": "DataProduct",
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "dd6ec49f-cd76-48cc-b6b8-ffbc71e8731e",
            "sourceColumn": "DataProductId",
            "sourceLineageTag": "db0c9ab9-0f2d-4fed-8b70-b2279dac8c4f",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductDisplayName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "2e8f94fc-5074-429a-84a3-07ba14bdc490",
            "sourceColumn": "DataProductDisplayName",
            "sourceLineageTag": "a39dbf37-4089-4f07-9552-4da49c3b6fa4",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "e2225a66-9a9f-43f4-9948-d87acd3d78d5",
            "sourceColumn": "DataProductType",
            "sourceLineageTag": "5f618f6d-0ac1-4f60-be42-32cf40567a53",
            "summarizeBy": "none"
          },
          {
            "name": "HasValidOwner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3a339f2b-38fc-4518-b4c0-124c6b04f74c",
            "sourceColumn": "HasValidOwner",
            "sourceLineageTag": "df42f1c6-5b80-4516-8bf4-e96394cb19cd",
            "summarizeBy": "none"
          },
          {
            "name": "HasValidUseCase",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "edb5e88f-ee0e-4b01-a819-e69fa13ce786",
            "sourceColumn": "HasValidUseCase",
            "sourceLineageTag": "ad4067cc-72a9-4c38-a947-45a17093c2e7",
            "summarizeBy": "none"
          },
          {
            "name": "AssetCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f01fde53-a9c8-4f8a-978c-dba17d68aac2",
            "sourceColumn": "AssetCount",
            "sourceLineageTag": "26f5dc91-2a0f-4962-9798-ce1088adf767",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "b4cc0a58-d37a-47b3-9a0a-8de61d7ed8d7",
            "sourceColumn": "CreatedAt",
            "sourceLineageTag": "ae87c72b-772c-4500-9c27-b6b2c94fe6c0",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "3b28dc33-63c6-4339-b36e-ff5cebe0b7e2",
            "sourceColumn": "CreatedBy",
            "sourceLineageTag": "a8dd7633-e73e-46bd-9571-6a4c7e1d361d",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "2a439fe1-db3f-4d4f-bfb2-b618af137849",
            "sourceColumn": "ModifiedAt",
            "sourceLineageTag": "0b0cabc2-f4a3-463a-ae80-93532959cbab",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "a5cf48d6-0d0b-4d6a-80ed-98c7f6a62bbc",
            "sourceColumn": "ModifiedBy",
            "sourceLineageTag": "5707fdc7-b70b-41f4-91a2-c96f61b6b2f1",
            "summarizeBy": "none"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "f40d526f-4ad2-46f1-bd06-51b33d07e260",
            "sourceColumn": "LastRefreshedAt",
            "sourceLineageTag": "cee8dcaf-70f8-47bf-a718-f7ad440326ac",
            "summarizeBy": "none"
          },
          {
            "name": "IsAuthoritativeSource",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "374e9979-1eaf-40ac-85af-cdab958601e0",
            "sourceColumn": "IsAuthoritativeSource",
            "sourceLineageTag": "cea7db2f-53b8-4e69-acb3-fd6b1649028d",
            "summarizeBy": "none"
          },
          {
            "name": "HasDataQualityScore",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "6adddd11-3ede-4a73-8c17-d6d41b061150",
            "sourceColumn": "HasDataQualityScore",
            "sourceLineageTag": "0ab26c16-e9bf-4c61-8e4d-f486721fd7f4",
            "summarizeBy": "none"
          },
          {
            "name": "ClassificationPassCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "01b43a99-8139-4fb7-b1b4-0a1af4589e49",
            "sourceColumn": "ClassificationPassCount",
            "sourceLineageTag": "8a126b99-65c8-4d6d-b958-ea8d100c1eba",
            "summarizeBy": "none"
          },
          {
            "name": "HasAccessEntitlement",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ee326a0c-9b1c-4c72-b2b3-68dfd44b9bba",
            "sourceColumn": "HasAccessEntitlement",
            "sourceLineageTag": "c59ed45b-910b-4e22-b602-d694829cdf81",
            "summarizeBy": "none"
          },
          {
            "name": "HasDataShareAgreementSetOrExempt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "ce7f856d-8b67-4c7d-aa57-5990b1009391",
            "sourceColumn": "HasDataShareAgreementSetOrExempt",
            "sourceLineageTag": "79ad4ed1-5623-40f6-8aa7-ad0cbe8e95c0",
            "summarizeBy": "none"
          },
          {
            "name": "GlossaryTermCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b29bf82c-b954-4e4e-8f11-59bc5f3142b5",
            "sourceColumn": "GlossaryTermCount",
            "sourceLineageTag": "4a8c05c3-f5c0-4fd9-9d4d-c75e6fd2a351",
            "summarizeBy": "none"
          },
          {
            "name": "Access entitlement P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "951d13e0-b7f7-4070-b0e5-de6c55c1fc20",
            "sourceColumn": "Access entitlement P/F",
            "sourceLineageTag": "6c0ec664-d767-456c-b0e1-0a53e842f4ad",
            "summarizeBy": "none"
          },
          {
            "name": "Action Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a4180bcf-f1a8-4b77-9b49-d7d438432b31",
            "sourceColumn": "Action Items",
            "sourceLineageTag": "2c87178d-3fa0-4f0d-9307-8a5c201c25f5",
            "summarizeBy": "none"
          },
          {
            "name": "Authoritative source P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "3284d575-2729-46f5-9c2a-902b0d85c47f",
            "sourceColumn": "Authoritative source P/F",
            "sourceLineageTag": "91d8f8a6-65af-4f4b-95a4-19b3bb8a1f57",
            "summarizeBy": "none"
          },
          {
            "name": "Classification_Product P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "be8cb085-ed34-4268-9f20-e4abbab5c5d8",
            "sourceColumn": "Classification_Product P/F",
            "sourceLineageTag": "76d2386b-502f-4748-8ea5-5fa921ae906e",
            "summarizeBy": "none"
          },
          {
            "name": "Data consumption purpse P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "9e407b64-9ef6-4a70-9c90-7c3e175c2ebc",
            "sourceColumn": "Data consumption purpse P/F",
            "sourceLineageTag": "ba828d2a-4632-4b29-896c-d8f6e0d8cd47",
            "summarizeBy": "none"
          },
          {
            "name": "Data Qualiy P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "cacb3105-9c76-4d7a-b4d8-ebc04f5df947",
            "sourceColumn": "Data Qualiy P/F",
            "sourceLineageTag": "9811b820-10ba-44d4-b769-3f6304e5d90a",
            "summarizeBy": "none"
          },
          {
            "name": "Overall health staus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "7254272e-3bb1-4180-ad20-9b8a65b7a516",
            "sourceColumn": "Overall health staus",
            "sourceLineageTag": "7314c5a9-fc97-430a-bc17-e2a197b06216",
            "summarizeBy": "none"
          },
          {
            "name": "Owner P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "54f98048-7c8d-4269-8710-2be1bc1bc445",
            "sourceColumn": "Owner P/F",
            "sourceLineageTag": "1116f6a1-d103-4170-bd5b-e588adb8cd8e",
            "summarizeBy": "none"
          },
          {
            "name": "Owner_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "61d0321b-2549-4c08-a670-1271afcbcb82",
            "sourceColumn": "Owner_catalog P/F",
            "sourceLineageTag": "e56a65f7-dc4d-4a3e-ae24-a41ef7700310",
            "summarizeBy": "none"
          },
          {
            "name": "Valid use case_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "82022489-ab54-4e54-b1c8-ea4115e9c581",
            "sourceColumn": "Valid use case_catalog P/F",
            "sourceLineageTag": "139fa52e-a368-4695-93c7-436fab867a0f",
            "summarizeBy": "none"
          },
          {
            "name": "Assetcount_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "38a61852-73a5-4a0c-a0a9-0e11f01a6202",
            "sourceColumn": "Assetcount_catalog P/F",
            "sourceLineageTag": "239fc81e-0ed9-4c93-91be-4b1f38cce209",
            "summarizeBy": "none"
          },
          {
            "name": "Description_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "9a07d9d5-27d4-4104-86a7-9710917152c0",
            "sourceColumn": "Description_catalog P/F",
            "sourceLineageTag": "46edeabd-ad87-4538-ad4b-c9c6d0498c79",
            "summarizeBy": "none"
          },
          {
            "name": "Glosssary Term count_catalog P/F",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "5f99f4ed-0ec3-47f6-b57d-b47ee8a70b2f",
            "sourceColumn": "Glosssary Term count_catalog P/F",
            "sourceLineageTag": "57cd768e-7c5e-4485-a4d2-55926428d5e9",
            "summarizeBy": "none"
          },
          {
            "name": "HasDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "57a4b426-5053-4961-8e67-1736545f8b40",
            "sourceColumn": "HasDescription",
            "sourceLineageTag": "f02d5487-6225-4e9b-a0c9-b38067c34ce8",
            "summarizeBy": "none"
          },
          {
            "name": "DataProductStatus",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "784d1ec5-4833-410e-b914-5319cb8ee4b8",
            "sourceColumn": "DataProductStatus",
            "sourceLineageTag": "7e8f44bf-9d58-4d66-9c63-391fccaaa750",
            "summarizeBy": "none"
          },
          {
            "name": "HasValidTermsOfUse",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "e786f3a1-2053-4a5e-a904-798b3140bdc2",
            "sourceColumn": "HasValidTermsOfUse",
            "sourceLineageTag": "0ea5692f-10b8-4d07-8843-fa94aae7f127",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e898a223-127c-4b89-9067-b9fa2f5e9d4a",
        "measures": [
          {
            "name": "1C2_Ownership",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1C2_Ownership\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "4ac01e1f-a2e4-441e-bcca-c3eb9ec5b22a",
            "sourceLineageTag": "ab20c77a-ed22-412c-9aee-96f1d4093cbc"
          },
          {
            "name": "1C3_Authoritative source",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1C3_Authoritative source\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "3024d490-7903-4f04-a272-608cfa13fe11",
            "sourceLineageTag": "635f12d3-631e-4325-9a8a-8e8e3ea0c0de"
          },
          {
            "name": "1C5_Catalog",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1C5_Catalog\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7adacdc7-2b65-4136-843d-11988d51cd74",
            "sourceLineageTag": "2ab18bee-5cb3-41cc-b2a9-e3ffe7150910"
          },
          {
            "name": "1C6_Classification",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1C6_Classification\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b04ac020-7077-4e57-8feb-3dcb4780aef3",
            "sourceLineageTag": "257a6f65-ca40-4a25-b60b-478186ade7b3"
          },
          {
            "name": "1C7_Access entitlement",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1C7_Access entitlement\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "3305edb2-7a49-4d90-ae75-c5c1d558cba0",
            "sourceLineageTag": "19dfa957-b968-4be9-bcaa-896dfe9fc6d5"
          },
          {
            "name": "1C8_Data consumption purpose",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1C8_Data consumption purpose\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "414bbd50-9f1f-4786-8a2a-abc4af95d839",
            "sourceLineageTag": "c3686e9a-4c21-4611-83dd-4fb0d92b4188"
          },
          {
            "name": "1Metadata completeness",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1Metadata completeness\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dee74d16-ac3c-4350-ba7e-714a4b0fdffa",
            "sourceLineageTag": "650c41d3-8546-4ba5-8be9-4014a82b1e24"
          },
          {
            "name": "1Overall health score",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1Overall health score\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "8c43773a-94ba-4397-a3a7-67a67d659dac",
            "sourceLineageTag": "5e767785-8cdd-406c-9a48-d0c068bec8c4"
          },
          {
            "name": "1Quality",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1Quality\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e6c5b7c1-117d-41c5-8564-82cc02eebc8d",
            "sourceLineageTag": "30116691-0393-410a-b703-19c76e84b690"
          },
          {
            "name": "1Use",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1Use\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2cb84f3a-db77-422c-baf8-2d4de6173d28",
            "sourceLineageTag": "ddd54794-cd9b-4f80-90a3-8a2a29048a01"
          },
          {
            "name": "Access entitlement health staus",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Access entitlement health staus\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "43a09c63-8103-4f28-80c3-0220c8bacc69",
            "sourceLineageTag": "b7ffffc4-0719-43cb-a79d-53279abc5873"
          },
          {
            "name": "Access entitlement Pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Access entitlement Pass count\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "7884cf00-eac4-4183-ba63-8fcda6750e6b",
            "sourceLineageTag": "40fa872f-835e-4679-9052-8f8547a37610"
          },
          {
            "name": "Access entitlement tresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Access entitlement tresh hold\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "c5b9663c-2577-4d55-b0ec-d88732e86a65",
            "sourceLineageTag": "ab5ad6bc-ff85-4d61-9b24-bd5c3772d3c2"
          },
          {
            "name": "Action item measure",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Action item measure\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "13494c09-e850-4ce1-b65a-119958f2e8c2",
            "sourceLineageTag": "990c4ec0-d8bc-4f27-9879-86b4bce80455"
          },
          {
            "name": "Authoritative source health staus",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Authoritative source health staus\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "96e967ce-f12e-4afe-ad70-3b217b7e9539",
            "sourceLineageTag": "444d4604-3386-4cd4-846d-c320bf253902"
          },
          {
            "name": "Authoritative source Pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Authoritative source Pass count\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "e591db5c-cbaa-4bee-b445-ddc1debf0718",
            "sourceLineageTag": "887ea7f2-bcf9-4962-8f16-bc744e1906ca"
          },
          {
            "name": "Authoritative tresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Authoritative tresh hold\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "baf31c8c-68c0-411f-b955-cbdb92004c6a",
            "sourceLineageTag": "359dfd36-0299-4bb5-b9d1-2e77a355652e"
          },
          {
            "name": "C_12 Data quality",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"C_12 Data quality\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b48e1aa6-36f1-4141-a934-1174b95cc0b1",
            "sourceLineageTag": "f315a253-ecdf-47db-bc8e-1c358c0d9030"
          },
          {
            "name": "C2_Ownership",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"C2_Ownership\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a048d160-d89c-4ba9-8120-c7e7fcf58751",
            "sourceLineageTag": "d0af49fd-f713-48b2-95ad-6d80adaabd97"
          },
          {
            "name": "C3_Authoritative source",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"C3_Authoritative source\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "728b1f99-efe5-4b79-b834-e90793035a6a",
            "sourceLineageTag": "5a5e09ab-0409-411f-a714-a3e844d3ef85"
          },
          {
            "name": "C5_Catalog",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"C5_Catalog\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "e77690e6-85ab-4c29-9149-3f7dcd6743de",
            "sourceLineageTag": "566f3007-80ea-4c64-990d-790539da87d1"
          },
          {
            "name": "C6_Classification",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"C6_Classification\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "ba6b8d00-f889-4fc9-a647-7b041eb2f812",
            "sourceLineageTag": "0057267d-3af5-4f98-a98b-c975fb2a8b03"
          },
          {
            "name": "C7_Access entitlement",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"C7_Access entitlement\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7fba5d66-03bd-4b38-a4aa-33e9f6b9197a",
            "sourceLineageTag": "c41438bc-0a9a-46a9-af5d-11475af66d9a"
          },
          {
            "name": "C8_Data consumption purpose",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"C8_Data consumption purpose\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5cca4288-87fb-46ff-8da5-5ecdb41c1d5a",
            "sourceLineageTag": "58960f74-44b3-4bd4-8ee0-df42002d83c1"
          },
          {
            "name": "Catalog health staus",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Catalog health staus\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "58b659d4-5cbb-4aa2-a20a-8c26e64c1c68",
            "sourceLineageTag": "2a781147-eb50-4ffd-8e3e-a8281d71e158"
          },
          {
            "name": "Catalog Pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Catalog Pass count\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "98c5d954-381f-43d1-9852-e47899e48754",
            "sourceLineageTag": "799eeb76-a960-45bc-b976-1b177791ec26"
          },
          {
            "name": "Catalog tresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Catalog tresh hold\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "ad3dc0ff-58c7-473b-8ac0-332d3313b46d",
            "sourceLineageTag": "3bb0813d-0b95-41cb-8b4f-431a75220e91"
          },
          {
            "name": "Classifiaction pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Classifiaction pass count\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "f319dfde-0b7c-48bd-b92f-ad63c543a2b9",
            "sourceLineageTag": "88716b25-a863-4e04-82b3-6d65fd5d6a5e"
          },
          {
            "name": "Classification health staus",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Classification health staus\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "6a28e1fc-d2fe-406c-821c-b8e2d620df05",
            "sourceLineageTag": "e84628c8-ec41-4236-859e-21354ed88f44"
          },
          {
            "name": "Classification tresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Classification tresh hold\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "206c29ec-adea-40ba-b750-64e7a0453443",
            "sourceLineageTag": "836b6889-86bd-4a9a-bcb6-0ad1a4aac353"
          },
          {
            "name": "Data consumption health staus",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Data consumption health staus\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "c72ef5de-1ed9-493a-a9d3-31e7ec9628fb",
            "sourceLineageTag": "dace400e-2202-4a1b-9219-705a20357aa3"
          },
          {
            "name": "Data consumption Purpose Pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Data consumption Purpose Pass count\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "aa2a98a2-54bc-4cc5-a2f2-ae120ace95d5",
            "sourceLineageTag": "7855a0ec-41a3-4265-b313-0bf7207d60ca"
          },
          {
            "name": "Data consumption tresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Data consumption tresh hold\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "6f6bc286-e7d5-4ee5-b3b5-1babbc29d1d6",
            "sourceLineageTag": "81caf6f8-0f01-4a0b-a430-909b617658e0"
          },
          {
            "name": "Data quality health staus",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Data quality health staus\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "db41b1c2-ea99-4623-83c6-5e03d8a966f2",
            "sourceLineageTag": "416e646a-07c2-4fc1-bfe7-acee39ce095d"
          },
          {
            "name": "Data Quality Pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Data Quality Pass count\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "02473647-6776-4ead-bee8-71cea90f9386",
            "sourceLineageTag": "8de7c777-329d-47d5-8454-a6299c3491a4"
          },
          {
            "name": "Data quality tresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Data quality tresh hold\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "c71887bc-9e4a-435d-a1c5-b36a1cadd86a",
            "sourceLineageTag": "1bbf4b86-b8ab-409f-b8d7-5ae433350070"
          },
          {
            "name": "DummyTarget",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"DummyTarget\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "7f6f129a-810d-4f98-9ca9-e56b719ade92",
            "sourceLineageTag": "bbf2d5af-8953-4ec0-8fcf-1047219c5f74"
          },
          {
            "name": "Max_Thresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Max_Thresh hold\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "642a18f4-ecd5-4de9-9e32-d2e334dc78bc",
            "sourceLineageTag": "9a461d76-b808-4fda-8d19-7b073bc50ee8"
          },
          {
            "name": "Metadata completeness",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Metadata completeness\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "5099323e-3f41-46db-93bf-d92ba8e20c37",
            "sourceLineageTag": "dc3bd2a5-c74d-4898-9517-f75fbf05fe29"
          },
          {
            "name": "Metadata completeness status",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Metadata completeness status\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "fc5af0b9-0e25-409b-b224-f3fa49bb4232",
            "sourceLineageTag": "b4cb6f86-f8f9-49ee-9c09-f9bad0b250f7"
          },
          {
            "name": "Metadata completeness tresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Metadata completeness tresh hold\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "c59f1e89-66f3-4010-9a0e-efa2f469a126",
            "sourceLineageTag": "090cf046-3d2f-45ef-aa54-51b8fe474c28"
          },
          {
            "name": "Min_Tresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Min_Tresh hold\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "1aca2493-9202-4eb2-a186-86c59bddcb16",
            "sourceLineageTag": "e380079a-7aa7-45db-9608-733f7581af21"
          },
          {
            "name": "Overall health score",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Overall health score\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2e9ee8ac-4c55-4a06-82cf-093ef14a4a0e",
            "sourceLineageTag": "01d5ba84-97cc-4e95-9017-5e4f00782ca0"
          },
          {
            "name": "Overall health staus_measure",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Overall health staus_measure\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "381ef05b-fca0-4e70-8f8b-1a6dfb943fd2",
            "sourceLineageTag": "33398188-377a-4f82-a59c-b2033adfe038"
          },
          {
            "name": "Overall health thresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Overall health thresh hold\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "e2d446e4-4dfe-418f-9839-fd999c552947",
            "sourceLineageTag": "bb297018-9b5e-4f7a-b5ea-f4ad72911b4a"
          },
          {
            "name": "Owner Pass count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Owner Pass count\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "01751dcc-12b0-402b-9771-c1ebd58eb833",
            "sourceLineageTag": "d9c88924-6f6f-4069-9fcd-3ab22c711971"
          },
          {
            "name": "Ownership health staus",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Ownership health staus\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "0e434a8c-ca96-4901-9c24-b84f13282c5c",
            "sourceLineageTag": "a7988ff8-6a26-4a75-9e5f-9c989dd2227d"
          },
          {
            "name": "Ownership tresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Ownership tresh hold\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "be6cc990-c30f-4aa1-90f8-1b77ccb0f486",
            "sourceLineageTag": "14a55b68-dcfc-479a-acd4-5f9472bd377e"
          },
          {
            "name": "Quality",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Quality\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "23b33a0a-276c-4be0-9d1e-5c3e580eb965",
            "sourceLineageTag": "19a378de-e683-4eb8-9dd6-789066e5383a"
          },
          {
            "name": "Quality health staus",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Quality health staus\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "01b86c6e-8476-418f-9da9-bb4d4a78be54",
            "sourceLineageTag": "ac883693-c0ec-4efd-b2c1-0b2702982e90"
          },
          {
            "name": "Quality tresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Quality tresh hold\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "b5ddb0e8-0170-42f6-b8c3-2d5d3cd76137",
            "sourceLineageTag": "e685dd30-db6a-4c37-9b1b-584a4af55873"
          },
          {
            "name": "Sum of Pass Metrics",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Sum of Pass Metrics\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "ba3a37d3-099d-4413-9883-0cfc24fcd5ed",
            "sourceLineageTag": "57d81210-f823-42ba-8773-d191d79199f8"
          },
          {
            "name": "Asset count",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Asset count\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "2671b8b3-8d9c-45e0-b94e-71dfcfea2ffd",
            "sourceLineageTag": "ac7da6b6-b54c-4b0d-97bc-443dfff75361"
          },
          {
            "name": "Total DataProducts",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Total DataProducts\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "e171a1b3-9d1e-46bd-bb3a-e578036e0d46",
            "sourceLineageTag": "b8618123-5a08-4245-9b93-1fb72213875e"
          },
          {
            "name": "Total Domains",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Total Domains\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "be996ef7-1c81-4960-845c-c52a044bf3d3",
            "sourceLineageTag": "8d3cc3df-6ae9-457d-befc-956cc7244cdc"
          },
          {
            "name": "Use",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Use\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "86ef54ca-9bcb-4d91-b2bc-ad59636f11f9",
            "sourceLineageTag": "90258d2d-877d-4687-bf47-dc06ea0b7bff"
          },
          {
            "name": "Use heath staus",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Use heath staus\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "7037bd00-99fb-4120-b7aa-b3af72155337",
            "sourceLineageTag": "457163e4-529f-40d5-8a95-ed5577b57980"
          },
          {
            "name": "Use tresh hold",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Use tresh hold\", STRING, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "lineageTag": "53e1abc0-737e-4ea1-86d2-91259a2544bd",
            "sourceLineageTag": "e7e0f6a9-3468-40be-8dbd-8e07ae198037"
          },
          {
            "name": "1C_12 Data quality",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1C_12 Data quality\", DOUBLE, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "00dc7d05-6fb5-4b76-9f68-ec9ce356a712",
            "sourceLineageTag": "39f71e58-9d38-47a8-9813-15580d99a782"
          },
          {
            "name": "Total assets",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Total assets\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "8aef164c-c31a-44ab-a176-498ce8f26bfc",
            "sourceLineageTag": "8ddc5f73-4a8d-468d-bf70-0a1fbd9938e0"
          },
          {
            "name": "Catalog Pass count_without owner pass",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"Catalog Pass count_without owner pass\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "e0467e02-2071-4772-9f89-7ec7862a5039",
            "sourceLineageTag": "9a73f50a-95ec-4eab-84d6-ba5b3e2f0f54"
          },
          {
            "name": "1c4",
            "dataCategory": "Uncategorized",
            "expression": "EXTERNALMEASURE(\"1c4\", INTEGER, \"DirectQuery to AS - Data_Governance_Dataset\")",
            "formatString": "0",
            "lineageTag": "ecdf78ca-de45-49c6-afd9-81b57c6c3c27",
            "sourceLineageTag": "538807c9-76df-4838-9b63-bf2647439f9c"
          }
        ],
        "partitions": [
          {
            "name": "DataProduct",
            "mode": "directQuery",
            "source": {
              "entityName": "DataProduct",
              "expressionSource": "DirectQuery to AS - Data_Governance_Dataset",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "5e64d8f2-a51a-4abe-b8b8-86d5ed754fb7"
      },
      {
        "name": "DataProductContactAssociation",
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "3d9fae91-5ff3-41f3-9be4-2526ddcecf2c",
            "sourceColumn": "DataProductId",
            "sourceLineageTag": "f9228209-a9f2-48ef-bd76-3a4b3855747e",
            "summarizeBy": "none"
          },
          {
            "name": "ContactRole",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "ffe37be7-21e2-4200-99b1-4622e51d0202",
            "sourceColumn": "ContactRole",
            "sourceLineageTag": "f30a787a-b0a5-4e9b-99ca-c1c96923f277",
            "summarizeBy": "none"
          },
          {
            "name": "ContactId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "464fd307-f5cd-450d-a66b-616f351fafbc",
            "sourceColumn": "ContactId",
            "sourceLineageTag": "e30b29de-81e2-429f-abf9-eb516ac36939",
            "summarizeBy": "none"
          },
          {
            "name": "IsActive",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "3a8ae3a0-e1ef-43ec-926b-7a79c80be33e",
            "sourceColumn": "IsActive",
            "sourceLineageTag": "2e75d796-5478-4789-97c4-9f30ecb44d5d",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "38e3dc0e-a640-4ed9-a3e7-c73a81d41d2a",
        "partitions": [
          {
            "name": "DataProductContactAssociation",
            "mode": "directQuery",
            "source": {
              "entityName": "DataProductContactAssociation",
              "expressionSource": "DirectQuery to AS - Data_Governance_Dataset",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "31236631-10ef-425d-ad3a-df87513dc736"
      },
      {
        "name": "DataProductDataAssetAssociation",
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "39e8c60f-cb53-428b-bc9f-8323c60d7cd8",
            "sourceColumn": "DataProductId",
            "sourceLineageTag": "c6a82698-29c5-4e57-ab24-4276fd4c8e03",
            "summarizeBy": "none"
          },
          {
            "name": "DataAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "78b065bd-e9a8-4c9f-9ec2-ffe67208f7c3",
            "sourceColumn": "DataAssetId",
            "sourceLineageTag": "ab4f9105-383a-4b7e-a4bb-fbc40e175c00",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4bcf61ac-fe97-467b-a163-5dbfa75fa415",
        "partitions": [
          {
            "name": "DataProductDataAssetAssociation",
            "mode": "directQuery",
            "source": {
              "entityName": "DataProductDataAssetAssociation",
              "expressionSource": "DirectQuery to AS - Data_Governance_Dataset",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "85660211-deff-4cb3-963f-ed539531d13e"
      },
      {
        "name": "GlossaryTerm",
        "columns": [
          {
            "name": "TermId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "1aeb6865-8a36-4322-9c98-911c93ee38eb",
            "sourceColumn": "TermId",
            "sourceLineageTag": "14e859c0-8d1f-4bd1-8146-be3ae4bf8a77",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "4409c874-7b04-4fc5-bd07-c4bc6408816d",
            "sourceColumn": "Name",
            "sourceLineageTag": "f2c7d032-6498-42bb-969f-0116c9f20f57",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "ad5a06cd-d5a8-46f5-a99f-2897e0f5eb35",
            "sourceColumn": "CreatedAt",
            "sourceLineageTag": "77f893c4-b69a-42db-9e95-38e9a1c8a28e",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "5fe58a15-f558-4a27-a0ad-c68fdcdaa019",
            "sourceColumn": "ModifiedAt",
            "sourceLineageTag": "f9a348bf-7047-4a26-b7dd-6a3c6cefe972",
            "summarizeBy": "none"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "26ed14c3-5ba5-4444-be09-0f389efa9ed8",
            "sourceColumn": "Status",
            "sourceLineageTag": "036fe1e4-6b84-448f-a18c-4f78b720fc7c",
            "summarizeBy": "none"
          },
          {
            "name": "LastRefreshedAt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "dateTime",
            "formatString": "General Number",
            "lineageTag": "39ba4aa0-8ccb-4312-8646-dda6631959ac",
            "sourceColumn": "LastRefreshedAt",
            "sourceLineageTag": "d0d90a8c-f95f-49bc-90d4-4a016e6aea1c",
            "summarizeBy": "none"
          },
          {
            "name": "CreatedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "d34d3dbc-c905-444f-8165-d764d85c3c6c",
            "sourceColumn": "CreatedBy",
            "sourceLineageTag": "01de9a54-60f5-4435-a357-dfa5c8d72f9c",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedBy",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "a0f098d2-d991-4701-8b4f-60c9a0a59879",
            "sourceColumn": "ModifiedBy",
            "sourceLineageTag": "89655635-74a3-4199-962d-1e3dd2376f3b",
            "summarizeBy": "none"
          },
          {
            "name": "HasDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "7bd42777-f5ae-4591-b62e-860e1f0f18f1",
            "sourceColumn": "HasDescription",
            "sourceLineageTag": "b3d3da49-29fc-4bc5-b59b-354f9b12dea0",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "19f4d288-0b95-4151-88a4-2cd0e923f4f3",
        "partitions": [
          {
            "name": "GlossaryTerm",
            "mode": "directQuery",
            "source": {
              "entityName": "GlossaryTerm",
              "expressionSource": "DirectQuery to AS - Data_Governance_Dataset",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "11eca4bc-37b7-4418-8fab-8a61765a65a3"
      },
      {
        "name": "BusinessDomainDataProductAssociation",
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "360ee8e0-8617-45ec-89e8-11c6ca2d1499",
            "sourceColumn": "DataProductId",
            "sourceLineageTag": "82aec21e-2fc3-4feb-9de9-cb27d7d60b85",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "35d7a912-8636-4901-8f53-fe4d707cc1be",
            "sourceColumn": "BusinessDomainId",
            "sourceLineageTag": "31d95a76-065c-41f2-9c8a-a0af3fb3376a",
            "summarizeBy": "none"
          },
          {
            "name": "IsPrimaryDataProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "17409568-260d-41b7-866f-b596f35f655d",
            "sourceColumn": "IsPrimaryDataProduct",
            "sourceLineageTag": "77ce2fd1-dc06-4986-a76c-39943bdb7695",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "bd6ca825-cc88-4bcc-842b-8cb09ee5c723",
        "partitions": [
          {
            "name": "BusinessDomainDataProductAssociation",
            "mode": "directQuery",
            "source": {
              "entityName": "BusinessDomainDataProductAssociation",
              "expressionSource": "DirectQuery to AS - Data_Governance_Dataset",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "5f2992b4-bbe7-4efe-87a5-c806188552cd"
      },
      {
        "name": "AssetURLTable",
        "columns": [
          {
            "name": "DataProductId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "79d506a3-3877-4218-b8f3-a2750f33322b",
            "sourceColumn": "DataProductId",
            "sourceLineageTag": "30837126-41ed-462f-939f-cdc00c960993",
            "summarizeBy": "none"
          },
          {
            "name": "BusinessDomainId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "65820294-475b-498e-8bb7-1b64b7caeb8d",
            "sourceColumn": "BusinessDomainId",
            "sourceLineageTag": "aa401f1b-7db5-4011-a573-99d6d054dd13",
            "summarizeBy": "none"
          },
          {
            "name": "IsPrimaryDataProduct",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "isHidden": true,
            "lineageTag": "c8e27e9a-ed41-4b66-a0d2-b0e85fcf935a",
            "sourceColumn": "IsPrimaryDataProduct",
            "sourceLineageTag": "2a0bbd88-06c4-4644-ab26-7d0721f5e531",
            "summarizeBy": "none"
          },
          {
            "name": "DataAssetId",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "2eefb169-1f1c-401d-a10e-22a6da9080a2",
            "sourceColumn": "DataAssetId",
            "sourceLineageTag": "30ae45dd-59e6-4e33-bc1b-1efce4ca13fb",
            "summarizeBy": "none"
          },
          {
            "name": "Asset link",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "int64",
            "isHidden": true,
            "lineageTag": "ea7d6d35-f48b-4520-bd6e-872155458ae3",
            "sourceColumn": "Asset link",
            "sourceLineageTag": "d608b6c8-75c3-466a-96fd-dfe5cce1f8b6",
            "summarizeBy": "none"
          }
        ],
        "isHidden": true,
        "lineageTag": "005ed478-d2c7-4b3d-84bd-09c9018dea53",
        "partitions": [
          {
            "name": "AssetURLTable",
            "mode": "directQuery",
            "source": {
              "entityName": "AssetURLTable",
              "expressionSource": "DirectQuery to AS - Data_Governance_Dataset",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "1639e4c0-750f-43a3-8f2b-1074ddd39421"
      },
      {
        "name": "AccountInfo",
        "columns": [
          {
            "name": "TenantID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "Uncategorized",
            "dataType": "string",
            "lineageTag": "a8a694cf-fabb-41f0-b737-560aed16ca07",
            "sourceColumn": "TenantID",
            "sourceLineageTag": "32e21685-22eb-47ae-8621-6d4b68a0a469",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "a20b4def-36b7-4e4f-be54-a0f7134b67e4",
        "partitions": [
          {
            "name": "AccountInfo",
            "mode": "directQuery",
            "source": {
              "entityName": "AccountInfo",
              "expressionSource": "DirectQuery to AS - Data_Governance_Dataset",
              "type": "entity"
            }
          }
        ],
        "sourceLineageTag": "ad76777b-f72a-4a5b-898b-edb5ce69c480"
      }
    ]
  }
}