table DimDQRuleName
	lineageTag: dc55d1fa-3c14-410e-bfe3-ecd1274073e7

	column DQRuleId
		dataType: int64
		formatString: 0
		lineageTag: f6d955c0-c30e-496f-b97b-e2bd09234c20
		summarizeBy: none
		sourceColumn: DQRuleId

		annotation SummarizationSetBy = Automatic

	column DQRuleNameId
		dataType: string
		lineageTag: 4b5d6f97-cf3e-4716-8663-8f7b6d63ca7e
		summarizeBy: none
		sourceColumn: DQRuleNameId

		annotation SummarizationSetBy = Automatic

	column DQRuleNameSourceId
		dataType: string
		lineageTag: b7fd5f0d-a874-46d7-9828-88c6aa160060
		summarizeBy: none
		sourceColumn: DQRuleNameSourceId

		annotation SummarizationSetBy = Automatic

	column RuleName
		dataType: string
		lineageTag: 0f20da9c-02be-4f03-9a45-c4778ec953b9
		summarizeBy: none
		sourceColumn: RuleName

		annotation SummarizationSetBy = Automatic

	partition DimDQRuleName = m
		mode: import
		source =
				let
				    Source = Sql.Database(SERVER, DATABASE, [Query="select * from [" &DATABASE_SCHEMA& ".DimensionalModel].[DimDQRuleName]"]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"DQRuleNameDisplayName", "RuleName"}}),
				    #"Merged Queries" = Table.NestedJoin(#"Renamed Columns", {"DQRuleId"}, FactDataQuality, {"DQRuleId"}, "FactDataQuality", JoinKind.Inner)
				in
				    #"Merged Queries"

	annotation PBI_ResultType = Table

