table FactDataQuality
	lineageTag: 7c453522-8e61-4115-881c-fb091f4e2c25

	measure 'Passed Count' = sumx(keepfilters(FactDataQuality),FactDataQuality[DQPassedCount])
		formatString: 0
		lineageTag: d71b2758-e979-4bdb-9056-2d35e1e8336e

	measure RuleCount = distinctcount(FactDataQuality[DQRuleId])
		formatString: 0
		lineageTag: 084e00c9-3d45-42ee-b7e8-d12eb69d9b92

	measure TotalRows = sumx(keepfilters(FactDataQuality),FactDataQuality[TotalRowCount])
		formatString: 0
		lineageTag: 74e72b33-60d0-4dac-bd55-d67ba773ea4c

	measure TotalRows_UX = sumx(keepfilters(FactDataQuality),FactDataQuality[TotalRowCount__UX])
		formatString: 0
		lineageTag: 02903892-eb98-49f1-8de5-e1ce8c6504e1

	measure Weight = divide([RuleCount],calculate([RuleCount],removefilters(FactDataQuality)),0)
		lineageTag: 0f06a1e8-5f45-47de-ad94-53b1a4663263

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure WeightedPass = [Passed Count]*[Weight]
		lineageTag: 0dba9624-a5da-44ed-994d-66e812d8fe43

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure WeightedTotal = [TotalRows]*[Weight]
		lineageTag: a478e66c-903a-426b-8193-305e5975fc0d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure WeightedScore = divide([WeightedPass],[WeightedTotal],0)
		lineageTag: 7eaf128e-ca8a-45c0-8495-28e81e25340c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DQRuleId
		dataType: int64
		formatString: 0
		lineageTag: e66f20bf-2ed9-4e6d-b173-1ce69f94d96d
		summarizeBy: none
		sourceColumn: DQRuleId

		annotation SummarizationSetBy = Automatic

	column RuleScanCompletionDatetime
		dataType: dateTime
		formatString: General Date
		lineageTag: d5841fad-56eb-4a72-a4ba-6fdcf6d2d249
		summarizeBy: none
		sourceColumn: RuleScanCompletionDatetime

		variation Variation
			isDefault
			relationship: 83bd57a0-86ff-49b5-b809-34405a03e9f3
			defaultHierarchy: LocalDateTable_134159d7-f3be-40dc-8595-664439143ca3.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column BusinessDomainId
		dataType: string
		lineageTag: e2ffd0ce-6e88-4858-b748-64fab55e1c2f
		summarizeBy: none
		sourceColumn: BusinessDomainId

		annotation SummarizationSetBy = Automatic

	column DataProductId
		dataType: string
		lineageTag: 018e37d7-65ee-4366-8cc9-2dc63bff1466
		summarizeBy: none
		sourceColumn: DataProductId

		annotation SummarizationSetBy = Automatic

	column DataAssetId
		dataType: string
		lineageTag: a8fccfa1-ed7f-4cbc-9062-6e89ed503555
		summarizeBy: none
		sourceColumn: DataAssetId

		annotation SummarizationSetBy = Automatic

	column DQRuleTypeId
		dataType: int64
		formatString: 0
		lineageTag: b8142994-cbcf-46b1-ae9e-149202df8c66
		summarizeBy: none
		sourceColumn: DQRuleTypeId

		annotation SummarizationSetBy = Automatic

	column DQScanProfileId
		dataType: int64
		formatString: 0
		lineageTag: c1bb808a-7d21-4818-998c-5d1995a14e33
		summarizeBy: none
		sourceColumn: DQScanProfileId

		annotation SummarizationSetBy = Automatic

	column ScanCompletionDateId
		dataType: int64
		formatString: 0
		lineageTag: aed7031f-b1d3-4e9e-8318-4634cd7f331e
		summarizeBy: count
		sourceColumn: ScanCompletionDateId

		annotation SummarizationSetBy = Automatic

	column DQOverallProfileQualityScore
		dataType: double
		formatString: 0.00
		lineageTag: 8dd2fae1-d527-42b9-ae8f-46c4b657b04a
		summarizeBy: sum
		sourceColumn: DQOverallProfileQualityScore

		annotation SummarizationSetBy = Automatic

	column DQPassedCount
		dataType: int64
		formatString: #,0
		lineageTag: 6fcdfe59-b2ce-4310-ad28-3836f55fa913
		summarizeBy: sum
		sourceColumn: DQPassedCount

		annotation SummarizationSetBy = Automatic

	column DQFailedCount
		dataType: int64
		formatString: #,0
		lineageTag: 8f4ea6b9-2a4a-4ae7-92ab-cc78b87516fd
		summarizeBy: sum
		sourceColumn: DQFailedCount

		annotation SummarizationSetBy = Automatic

	column DQIgnoredCount
		dataType: int64
		formatString: #,0
		lineageTag: 4d2a4cb5-a38e-4ae6-8bf4-48c4e05a45cf
		summarizeBy: sum
		sourceColumn: DQIgnoredCount

		annotation SummarizationSetBy = Automatic

	column DQEmptyCount
		dataType: int64
		formatString: #,0
		lineageTag: 041feae8-150d-4270-8fad-ca830235ad7d
		summarizeBy: sum
		sourceColumn: DQEmptyCount

		annotation SummarizationSetBy = Automatic

	column DQMiscastCount
		dataType: int64
		formatString: #,0
		lineageTag: 3ad0d50d-0edb-42da-8323-ad3dc10f44a9
		summarizeBy: sum
		sourceColumn: DQMiscastCount

		annotation SummarizationSetBy = Automatic

	column TotalRowCount = FactDataQuality[DQPassedCount] + FactDataQuality[DQFailedCount] + FactDataQuality[DQEmptyCount] + FactDataQuality[DQIgnoredCount] + FactDataQuality[DQMiscastCount]
		dataType: int64
		formatString: 0
		lineageTag: 99f07b0e-b860-42ce-8d5e-c5654eee3ac4
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column TotalUnHealthyRowCount = ```
			FactDataQuality[DQFailedCount] + FactDataQuality[DQEmptyCount] + FactDataQuality[DQIgnoredCount] + FactDataQuality[DQMiscastCount] 
			```
		dataType: int64
		formatString: 0
		lineageTag: 60ad35fc-1642-4b2f-9000-633cee9a1547
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column Pass/Fail = IF(FactDataQuality[DQPassedCount] = FactDataQuality[TotalRowCount],"Pass","Fail")
		dataType: string
		lineageTag: 31badad0-e4c2-4126-b189-83cce7713d5e
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column ActionItemsRowCount = IF(FactDataQuality[Pass/Fail] = "Pass",0, FactDataQuality[DQFailedCount])
		dataType: int64
		formatString: 0
		lineageTag: a8cbaa70-e173-438e-a2ee-c3d8d70cdd9e
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column JobTypeId
		dataType: int64
		formatString: 0
		lineageTag: cf6e6c64-92fb-4759-9788-ce25912da6fc
		summarizeBy: none
		sourceColumn: JobTypeId

		annotation SummarizationSetBy = Automatic

	column IsEmpty = IF(FactDataQuality[DQEmptyCount] > 0, "Yes","No")
		dataType: string
		lineageTag: 5c336a3f-6597-43d4-a3e4-78ebd85efab5
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column IsIgnored = IF(FactDataQuality[DQIgnoredCount] > 0, "Yes","No")
		dataType: string
		lineageTag: aea550cf-ef64-4c90-b0d7-f7e668189bca
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column IsMiscast = IF(FactDataQuality[DQMiscastCount] > 0, "Yes","No")
		dataType: string
		lineageTag: b2019bc5-db73-4b13-8fd1-70aafbca3c3a
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column TotalRowCount__UX =
			SWITCH (TRUE,
			                RELATED(DimDQRuleType[RuleTypeName]) = "Like",FactDataQuality[DQPassedCount]+FactDataQuality[DQFailedCount]+FactDataQuality[DQMiscastCount],RELATED(DimDQRuleType[RuleTypeName]) = "Enumeration",FactDataQuality[DQPassedCount]+FactDataQuality[DQFailedCount]+FactDataQuality[DQMiscastCount],RELATED(DimDQRuleType[RuleTypeName]) = "Regex",FactDataQuality[DQPassedCount]+FactDataQuality[DQFailedCount]+FactDataQuality[DQMiscastCount], RELATED(DimDQRuleType[RuleTypeName]) = "Unique",FactDataQuality[DQPassedCount]+FactDataQuality[DQFailedCount]+FactDataQuality[DQMiscastCount],RELATED(DimDQRuleType[RuleTypeName]) = "Duplicate",FactDataQuality[DQPassedCount]+FactDataQuality[DQFailedCount]+FactDataQuality[DQMiscastCount],RELATED(DimDQRuleType[RuleTypeName]) = "CustomTruth",FactDataQuality[DQPassedCount]+FactDataQuality[DQFailedCount]+FactDataQuality[DQMiscastCount],RELATED(DimDQRuleType[RuleTypeName]) = "ReferenceCheck",FactDataQuality[DQPassedCount]+FactDataQuality[DQFailedCount]+FactDataQuality[DQMiscastCount],RELATED(DimDQRuleType[RuleTypeName]) = "NotNull",FactDataQuality[DQPassedCount]+FactDataQuality[DQEmptyCount]+FactDataQuality[DQFailedCount]+FactDataQuality[DQMiscastCount],RELATED(DimDQRuleType[RuleTypeName])= "TypeMatch",FactDataQuality[DQPassedCount]+FactDataQuality[DQMiscastCount],1)
		dataType: int64
		formatString: 0
		lineageTag: a83b81b2-a303-43d1-a5f6-e1fe3231decf
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column RuleLevelScore_StaticDen = DIVIDE(FactDataQuality[DQPassedCount],FactDataQuality[TotalRowCount],0)
		dataType: double
		formatString: 0.00000%;-0.00000%;0.00000%
		lineageTag: e1347b00-2295-470a-8aa9-09b140a5a8ad
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column RuleLevelScore_DynDen = DIVIDE(FactDataQuality[DQPassedCount],FactDataQuality[TotalRowCount__UX],1)
		dataType: double
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: c298a7f9-643e-4a29-a195-359e809cf0c9
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column DQJobSourceId
		dataType: string
		lineageTag: 9286701e-315e-4a4a-a293-f197b6675b74
		summarizeBy: none
		sourceColumn: DQJobSourceId

		annotation SummarizationSetBy = Automatic

	column DEHLastProcessedDatetime
		dataType: dateTime
		formatString: General Date
		lineageTag: 812c1edf-fcd5-46c1-8c06-129819bf0db8
		summarizeBy: none
		sourceColumn: DEHLastProcessedDatetime

		variation Variation
			isDefault
			relationship: 78c4662f-7982-4dc1-8c27-520018a48a39
			defaultHierarchy: LocalDateTable_1f4cc31a-aa9c-440a-95a5-a47ac85bdec1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column HierarchyId
		dataType: string
		lineageTag: 2f7b1e63-7d0d-43d9-93f2-467d5c9aa523
		summarizeBy: none
		sourceColumn: HierarchyId

		annotation SummarizationSetBy = Automatic

	hierarchy DQHierarchy
		lineageTag: 8427dfe0-5aae-4c58-9497-fde994232da6

		level BusinessDomainId
			lineageTag: a51276fb-95a3-4300-abfa-5e13335449d2
			column: BusinessDomainId

		level DataProductId
			lineageTag: 3a598d4d-1a14-404a-8d19-59a8f001e5c4
			column: DataProductId

		level DataAssetId
			lineageTag: ed2af2b6-aee5-4596-9a65-c30b8fd48676
			column: DataAssetId

		level DQRuleId
			lineageTag: 38ce0c28-1c86-4386-ae8b-14fce00c1aca
			column: DQRuleId

	partition FactDataQuality = m
		mode: import
		source =
				let
				    Source = Sql.Database(SERVER, DATABASE, [Query="select * from [" &DATABASE_SCHEMA& ".DimensionalModel].[RPTDataQuality]"]),
				    #"Added custom" = Table.AddColumn(Source, "HierarchyId", each "{" & [BusinessDomainId] & "-" & [DataProductId] & "-" & [DataAssetId] & "}")
				in
				    #"Added custom"

	annotation PBI_ResultType = Table

